NIEDUUI-391: Surveys Table View: Use the same table components as in other tables
edulution-io/edulution-ui pull request #167
Opened 2024-09-12 11:19 UTC by maierdominik

JIRA: https://schulz-informatik.atlassian.net/browse/NIEDUUI-391

NIEDUUI-391:
    * Use `@tanstack/react-table` components
    * Define the columns and cell content for the new table creation method
    * Update the selection state from inside the cell definitions
    * Make sure that the sorting works

2024-10-28 07:57 UTC, TomlDev commented on apps/frontend/src/locales/de/translation.json
> +    "filesOrFoldersSelected": "{{selected}} von {{total}} Datei(n)/Ordner ausgewählt"
Ordner(n)

2024-10-28 08:04 UTC, TomlDev commented on apps/frontend/src/pages/Surveys/Tables/components/SurveyTable.tsx
> +            {table.getHeaderGroups().map((headerGroup) => (
use destructuring

2024-10-28 08:05 UTC, TomlDev commented on apps/frontend/src/pages/Surveys/Tables/components/SurveyTable.tsx
> +              table.getRowModel().rows.map((row) => (
use destructuring

2024-10-28 08:15 UTC, TomlDev commented on apps/frontend/src/pages/Surveys/Tables/components/SurveyTableColumns.tsx
The lines are a lot higher then in conferences/file manager, do you know why?

https://github.com/user-attachments/assets/439a792a-6efe-41af-80ad-f34d15309cba
I think the changes also make it strange to select because it already shows a pointer mouse when it's not clickable

2024-10-28 08:17 UTC, TomlDev commented on apps/frontend/src/locales/de/translation.json
![grafik](https://github.com/user-attachments/assets/b17c924f-b0de-4cd6-b038-258fa3eb156f)

2024-10-28 08:27 UTC, TomlDev commented on libs/src/survey/utils/sortSurveyByTitle.ts
> +function sortSurveyByTitle<T extends ObjectWithFormula>(a: T, b: T): number {
Why not use the `SurveyDto` when you sort surveys and not Objects?

2024-10-28 08:27 UTC, TomlDev commented on package-lock.json
Why was this changed?

2024-10-28 08:28 UTC, TomlDev commented on libs/src/survey/utils/sortSurveyByInvitesAndParticipation.ts
> +const sortSurveyByInvitesAndParticipation = <T extends ObjectWithInvites>(a?: T, b?: T): number => {
Why introduce some strange new types instead of using the `SurveyDto` when you sort surveys and not Objects?

2024-10-28 08:31 UTC, TomlDev commented on libs/src/survey/utils/convertJSONToSurveyFormula.ts
> +};
This makes no sense. Either you don't know the type of the JSON then you **can not** assert it's type.
Or you know the type of the JSON then you don't have to use this function (which is no real function at all).

Currently, it uses a simple type assertion, which could potentially introduce runtime errors if the JSON object does not match the `SurveyFormulaDto` structure. 

A better approach would involve actually validating or mapping the properties within `formula` to match `SurveyFormulaDto` fields. Here’s a refined suggestion:

```typescript
import SurveyFormulaDto from '@libs/survey/types/surveyFormula.dto';

const convertJSONToSurveyFormula = (formula: JSON): SurveyFormulaDto | undefined => {
  try {
    const parsedFormula = JSON.parse(JSON.stringify(formula)) as Partial<SurveyFormulaDto>;
    
    // Basic type checks (replace these with actual property checks as needed)
    if (parsedFormula.property1 && parsedFormula.property2) { // Adjust fields to match SurveyFormulaDto
      return parsedFormula as SurveyFormulaDto;
    }

    return undefined;
  } catch (error) {
    return undefined;
  }
};

export default convertJSONToSurveyFormula;
```

This approach ensures that only valid `SurveyFormulaDto` objects are returned. Additionally, adjusting the fields within `if` checks aligns with the specific properties in `SurveyFormulaDto`.

**BUT** from your usage it does not seem necessary.

2024-10-28 08:31 UTC, TomlDev requested changes
.

2024-10-29 12:41 UTC, TomlDev commented on apps/frontend/src/locales/de/translation.json
> +    "filesOrFoldersSelected": "{{selected}} von {{total}} Datei(n)/Ordner ausgewählt"
Yes, both were wrong 😭 

> „2 von 4 Dateien ausgewählt“ (Pluralform Dateien statt Datein)
> „2 von 4 Ordnern ausgewählt“ (Dativform Ordnern statt Ordner)

2024-10-29 12:42 UTC, maierdominik commented on apps/frontend/src/locales/de/translation.json
removed

_I thought that it would be nice to differentiate them a little so that the missing data is easier to spot_

2024-10-29 13:00 UTC, maierdominik commented on package-lock.json
After merging dev into this branch, 
I had to reset the node modules because the 
project graph was not able to be drawn.

2024-10-29 13:02 UTC, maierdominik commented on libs/src/survey/utils/sortSurveyByInvitesAndParticipation.ts
> +const sortSurveyByInvitesAndParticipation = <T extends ObjectWithInvites>(a?: T, b?: T): number => {
removed

I thought it would be nice to make it more generic

2024-10-29 14:44 UTC, maierdominik commented on libs/src/survey/utils/convertJSONToSurveyFormula.ts
> +};
I thought that i should not `parse` and `stringify` the `formula` to convert it
( https://github.com/edulution-io/edulution-ui/pull/167#discussion_r1810242446 )

For now i stayed with the conversation but i added the functionality to check for the resulting type.

In order to get the right structure I had to redefine the surveys formula type:
![image](https://github.com/user-attachments/assets/0116e3bc-0906-479a-abc5-a73a03d0d4a9)
![image](https://github.com/user-attachments/assets/91126f8e-c5b4-4a48-a885-bf199ee4f132)
![image](https://github.com/user-attachments/assets/9e8d3eef-50ba-479e-808e-e9853cf029aa)

And I added following structural tests:
![image](https://github.com/user-attachments/assets/3696213a-5ac1-455d-ac1a-d5ebc1cdccf1)
![image](https://github.com/user-attachments/assets/ea4dc463-6422-4682-b948-2b08dbedaadd)
![image](https://github.com/user-attachments/assets/4e7184c9-f09b-4859-83e5-48539586066e)

2024-10-29 16:08 UTC, maierdominik commented on libs/src/survey/utils/getSurveyTitle.ts
> +  const surveyFormula = convertJSONToSurveyFormula(survey.formula || {});
The typing of formula is now TSurveyFormula and for the `surveyjs` components that use it we convert it to a JSON type, so that atleast our dataset is clean typed.

2024-11-04 09:42 UTC, TomlDev commented on apps/frontend/src/locales/en/translation.json
> +        "description": "Here, you find the surveys that you have participated, already."
> The comma in your sentence is not necessary. It should be written as:
> 
>     Here you find the surveys that you have created by yourself.
> 
> The comma would only be needed if the phrase "Here" was being emphasized as an introductory clause with a pause (which is uncommon in short, informal sentences like this one).

2024-11-04 09:51 UTC, TomlDev commented on libs/src/survey/utils/sortSurveyByTitle.ts
> +function sortSurveyByTitle<T extends ObjectWithFormula>(a: T, b: T): number {
I am not asking to say what is right or wrong, I just want you to think about it and justify it 👍🏽 
If you think a more generic way is better it's not a problem, but in this case the name of the function/file was not generic because it has `survey` in it

2024-11-04 09:55 UTC, TomlDev commented on apps/frontend/src/pages/Surveys/Editor/components/SurveyEditor.tsx
> +    creator.JSON = formula as unknown as JSON;
Is the cast really necessary? I don't get errors with this:
![grafik](https://github.com/user-attachments/assets/126992f4-a5ea-4af1-a414-1d2261fc92d3)

(but sometimes eslint or the compiler is slow so I am not 100% sure)

2024-11-05 10:36 UTC, maierdominik commented on apps/frontend/src/locales/de/translation.json
> +    "filesOrFoldersSelected": "{{selected}} von {{total}} Datei(n)/Ordner ausgewählt"
![image](https://github.com/user-attachments/assets/64ff893d-9651-440f-b207-a05ca42cb21d)

2024-11-05 10:55 UTC, maierdominik commented on apps/frontend/src/pages/Surveys/Editor/components/SurveyEditor.tsx
> +    creator.JSON = formula as unknown as JSON;
Thx, it does make sense that this accepts an any typed value since it also returns an any type.

_- Therefore the type conversations in line 109 and 113 -_

2024-11-07 12:29 UTC, TomlDev commented on libs/src/survey/utils/isSurveyFormula.ts
> +    if (unStructuredPage) return false;
`
    return pages.every(isSurveyPage);`

2024-11-07 12:31 UTC, TomlDev commented on libs/src/survey/utils/isSurveyPage.ts
> +export default isSurveyPage;
Yes, this code can also be refactored for clarity and efficiency. We can use `every()` instead of `map()` and `find()` for a more direct approach. Here's the refactored version:

```javascript
import TSurveyPage from '@libs/survey/types/TSurveyPage';
import isSurveyElement from '@libs/survey/utils/isSurveyElement';

const isSurveyPage = (surveyFormula: TSurveyPage): boolean => {
  const { name, elements } = surveyFormula;

  if (!name || !elements) return false;

  // Check if all elements are valid
  return elements.every(isSurveyElement);
};

export default isSurveyPage;
```

### Changes made:
- **Combined checks**: The checks for `name` and `elements` are combined in a single `if` statement for simplicity.
- **Replaced `map()` and `find()` with `every()`**: This improves readability by directly returning whether all elements pass the `isSurveyElement` validation.

### Benefits:
- **Improved readability**: The code is easier to follow with `every()` clearly expressing the intent.
- **Simplified logic**: Fewer lines of code and no need to store intermediate arrays or search for unstructured elements separately.

This refactoring keeps the original behavior intact while making the code more concise and readable.

2024-11-07 12:32 UTC, TomlDev commented on libs/src/survey/utils/isSurveyElement.ts
> +  return !(!name || !type);
😂

2024-11-07 12:52 UTC, TomlDev commented on libs/src/survey/utils/convertJSONToSurveyFormula.ts
> +    // const parsedFormula = JSON.parse(JSON.stringify(formula)) as SurveyFormula;
Remove the comment

2024-11-07 12:54 UTC, TomlDev commented on libs/src/survey/constants/initial-survey-form.ts
> +    this.formula = selectedSurvey?.formula || ({ title: '' } as TSurveyFormula);
I think the cast is not necessary

2024-11-07 12:55 UTC, TomlDev commented on libs/src/survey/constants/empty-survey-form.ts
> +    this.formula = { title: '' } as TSurveyFormula;
This seems to be the same like an initial form without passing a `selectedSurvey`. I think it's duplicate code and not necessary, what do you think?

2024-11-07 13:04 UTC, TomlDev commented on apps/frontend/src/pages/Surveys/Tables/dialogs/CommitedAnswersDialogBody.tsx
> +  const surveyModel = new Model(formula as unknown as JSON);
Here we have `const formula: TSurveyFormula`, so:
```
  const surveyModel = new Model(JSON.stringify(formula));

2024-11-07 13:07 UTC, TomlDev commented on apps/frontend/src/pages/Surveys/Tables/dialogs/ResultTableDialogBody.tsx
> +        formula={selectedSurvey.formula as unknown as JSON}
What about changing 
```
interface ResultTableDialogBodyProps {
  formula: JSON;  // here to `formula: TSurveyFormula;`
  result: JSON[];
}

2024-11-07 13:08 UTC, TomlDev commented on apps/frontend/src/pages/Surveys/Tables/dialogs/ResultVisualizationDialogBody.tsx
> +      formula={selectedSurvey.formula as unknown as JSON}
What about changing 
```
interface ResultVisualizationDialogBodyProps {
  formula: JSON;  // here to `formula: TSurveyFormula;`
  result: JSON[];
}

2024-11-07 13:11 UTC, TomlDev commented on libs/src/survey/utils/convertJSONToSurveyFormula.ts
> +    const parsedFormula = formula as unknown as SurveyFormula;
You don't parse here something, it's only a type cast.

> If the main purpose is type-casting, **`typedFormula`** would be the most appropriate name:
> 
> ```typescript
> const typedFormula = formula as unknown as SurveyFormula;
> ```
> 
> This makes it clear that the variable is simply being cast to a specific type.

2024-11-07 13:12 UTC, TomlDev commented on libs/src/survey/utils/convertJSONToSurveyFormula.ts
> +    return undefined;
One question, what happens when an error is thrown and `undefined` is returned here?
What will happen when editing/saving with `undefined` as value?

2024-11-08 13:20 UTC, maierdominik commented on apps/frontend/src/pages/Surveys/Tables/dialogs/CommitedAnswersDialogBody.tsx
oh, i am missing a 't' in there

![image](https://github.com/user-attachments/assets/ba38fd25-a73f-42b3-8dae-7b7ba781f694)

2024-11-08 13:41 UTC, maierdominik commented on libs/src/survey/utils/convertJSONToSurveyFormula.ts
> +    return undefined;
Well now i throw an error that the structure has issues: 

![image](https://github.com/user-attachments/assets/426d074d-05fc-43d6-aabd-6d8478c91d13)

![image](https://github.com/user-attachments/assets/812c5e5f-c9bb-410a-9155-c86e8cb0bdc5)
![image](https://github.com/user-attachments/assets/62a94eef-735f-479f-a70b-541085767e31)

2024-11-14 09:29 UTC, TomlDev commented on apps/frontend/src/pages/Surveys/SurveysPage.tsx
> +          <CommittedAnswersDialog />
> In survey contexts, responses that have already been submitted or recorded are commonly referred to as:
> 
> 1. **Submitted Responses**
> 2. **Recorded Answers**
> 3. **Finalized Responses**
> 4. **Posted Responses**
> 5. **Completed Responses**
> 
> Each term conveys that the answers are finalized and no longer editable. For example:
> 
> - “You can view your **submitted responses** to the survey.”
> - “These are the **recorded answers** for your recent survey participation.” 
> 
> Choose the term that best fits the formality and clarity needed for your context.

2024-11-14 09:44 UTC, TomlDev requested changes
Some small adjustments

2024-11-14 18:41 UTC, maierdominik commented on libs/src/survey/utils/convertJSONToSurveyFormula.ts
> +    throw new Error(t(SurveyErrorMessages.SurveyFormulaStructuralError));
sorry, I removed it.

I was not sure if a toastr is enough but i removed it, since i didn't know what else to do in the parent component.

2024-11-14 18:42 UTC, maierdominik commented on apps/frontend/src/pages/Surveys/SurveysPage.tsx
> +          <CommittedAnswersDialog />
now called `submittedAnswers`

2024-11-15 09:39 UTC, Maddi02 commented on apps/frontend/src/pages/Surveys/Tables/components/SurveyTable.tsx
> +            ))
It’s merged :)

2024-11-15 10:28 UTC, TomlDev commented on apps/frontend/src/components/shared/LoadingIndicator.tsx
> +      id={id}
Revert,
next time better switch the base branch

2024-11-15 10:29 UTC, TomlDev commented on apps/frontend/src/pages/Surveys/Tables/components/ScrollableTableTemp.tsx
> +// TODO: Delete after merging: 243 Make table header sticky #248 (https://github.com/edulution-io/edulution-ui/pull/248/files) was merged
Update 👍🏽

2024-11-27 14:06 UTC, TomlDev commented on apps/frontend/src/components/shared/LoadingIndicator.tsx
> +const LoadingIndicator: React.FC<LoadingIndicatorProps> = ({ isOpen }) => (
Why was this changed?

2024-11-27 14:11 UTC, TomlDev approved these changes

2024-11-28 17:03 UTC, maierdominik commented on apps/frontend/src/components/shared/LoadingIndicator.tsx
> +const LoadingIndicator: React.FC<LoadingIndicatorProps> = ({ isOpen }) => (
I added it because it was introduced by MH in the PR where the new ScrollableReactTable component was introduced.
Before the PR from MH was merged, was the `id` parameter removed.
So I removed it here too.

2024-11-28 17:08 UTC, maierdominik commented on apps/frontend/src/components/shared/LoadingIndicator.tsx
> +const LoadingIndicator: React.FC<LoadingIndicatorProps> = ({ isOpen }) => (
Because it is not used, not once.

MH added it and used it for a short while in the PR #248.
Then he removed the usage but the parameter was still there.

2024-11-29 09:14 UTC, merged