NIEDUUI-378: Add Change Personal Data Dialog and functionality
edulution-io/edulution-ui pull request #174
Opened 2024-09-27 15:05 UTC by maierdominik

JIRA: https://schulz-informatik.atlassian.net/browse/NIEDUUI-378

NIEDUUI-378:
    * add backend functionality to pass the change request from our frontend to the lmn api
    * add the settings page where the user can change his user detail settings 
    * add a quickfix for the styling of the disabled input fields

2024-10-29 09:35 UTC, maierdominik commented on apps/frontend/src/pages/Dashboard/Quota.tsx
I extracted the QuotaBody.tsx since MC asked me to return the same info as in LMN.
Therefore we also show the Quota inside of the user details. So there is not only the Card where the Quota is displayed but also the UserSettingsDetailsPage.tsx.


LMN VIEW:
![LMN_VIEW_-_2024-10-29 10_23_27-](https://github.com/user-attachments/assets/d5f9fafd-1e59-49bf-bb4f-d13dc0124599)

EDU VIEW:
![EDU_VIEW_-_2024-10-29 10_32_58-edulution io](https://github.com/user-attachments/assets/860571df-f5e8-4a78-819e-f873208f0b0e)

2024-10-29 09:38 UTC, maierdominik commented on apps/frontend/src/pages/UserSettings/Details/QuotaBody.tsx
( See: https://github.com/edulution-io/edulution-ui/pull/174#discussion_r1816476577 )

To make it more obvious, I now renamed the QuotaBody.tsx to Quota.tsx and the Card that is displayed in the dashboard is now called QuotaCard.tsx.
Quota.tsx is now displayed inside of QuotaCard (dashboard) and UserSettingsDetailsPage (user details)

2024-10-29 09:45 UTC, maierdominik commented on apps/api/src/lmnApi/lmnApi.service.ts
> +    return false;
It does work, now i am really confused because it never did before when i erased the following line:
```
HTTP_HEADERS.Authorization]: `Bearer ${lmnApiToken}`,
```

2024-10-29 09:54 UTC, maierdominik commented on apps/api/src/lmnApi/lmnApi.service.ts
> +      return false;
I added the boolean values so I could return the succession state of the operation since it failed regulary.
Now, after going through the history of this file i recognize that I missunderstood the reason for the previous error, which is fixed in the new implementation.

2024-10-29 09:57 UTC, maierdominik commented on apps/api/src/lmnApi/lmnApi.service.ts
> +              [HTTP_HEADERS.Authorization]: `Bearer ${lmnApiToken}`,
It never worked before when i left following line out:
```
HTTP_HEADERS.Authorization]: `Bearer ${lmnApiToken}`,
```

The typings come from my previous mystake.

2024-10-29 10:00 UTC, maierdominik commented on apps/api/src/lmnApi/lmnApi.service.ts
> +        return true;
I always received an error returning null.
It seems that the update from dev branch fixed that.

2024-10-29 12:02 UTC, maierdominik commented on apps/frontend/src/pages/UserSettings/Details/UserSettingsDetailsForm.tsx
> +  const mailProxyField = { proxyAddresses: user?.proxyAddresses || [] };
I had to make the BadgeFormField.tsx more generic:

![image](https://github.com/user-attachments/assets/3a8020c8-76c1-41b9-bd7f-f1e11b6bb035)

_similar to FormField.tsx_

2024-10-31 12:31 UTC, TomlDev commented on apps/frontend/src/pages/UserSettings/Details/QuotaBody.tsx
Alright, thanks for clarification. I have not seen this 👍🏽

2024-10-31 12:34 UTC, TomlDev commented on apps/frontend/src/store/useLmnApiStore.ts
> +  patchUserDetails: (username: string, details: Partial<UpdateUserDetailsDto>) => Promise<boolean>;
I think it's better like this:
```
interface UseLmnApiStore {
...
  patchUserDetails: (details: Partial<UpdateUserDetailsDto>) => Promise<null>;
  reset: () => void;
}

....

      patchUserDetails: async (userDetails): Promise<null> => {
        set({ isPatchingUserLoading: true, error: null });
        try {
          const { lmnApiToken } = useLmnApiStore.getState();
          const response = await eduApi.post<null>(
            `${USER}`,
            { userDetails },
            { headers: { [HTTP_HEADERS.XApiKey]: lmnApiToken } },
          );
          return response.data;
        } catch (error) {
          handleApiError(error, set);
          return null;
        } finally {
          set({ isPatchingUserLoading: false });
        }
      },

2024-10-31 12:38 UTC, TomlDev commented on apps/frontend/src/pages/UserSettings/Details/UserSettingsDetailsPage.tsx
> +      { label: t('usersettings.details.name'), value: user?.name || '...' },
Hmm okay, I think "..." is not a good placeholder. The AI:

> Using "..." as a placeholder for missing data can create confusion and reduce clarity for several reasons:
> 
>     Ambiguity: The ellipsis (...) can imply that the data is still loading, that there’s an error, or that additional data will appear soon. This can mislead users, especially if they are expecting the field to update after a delay.
> 
>     Poor Accessibility: Screen readers may have difficulty conveying the meaning of "..." to visually impaired users, leading to a frustrating experience. A more descriptive placeholder like "Not Provided" or "Information Unavailable" is clearer and more accessible.
> 
>     Inconsistent Standards: In user interfaces, ellipses are often used to signal incomplete information (e.g., truncated text), loading states, or expandable items. Using them for missing data conflicts with these conventions, potentially making the interface feel inconsistent or unpolished.

2024-10-31 12:54 UTC, TomlDev commented on apps/frontend/src/pages/UserSettings/Details/UserSettingsDetailsPage.tsx
> +      { label: t('usersettings.details.name'), value: user?.name || '...' },
We agreed to use a component with translation "not available" in italics

2024-11-04 08:20 UTC, TomlDev commented on apps/frontend/src/pages/UserSettings/Security/components/PasswordChangeForm.tsx
> +            className="block text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
Can you explain to me the behavior of these classname changes?
The AI says this, but when is the peer element disabled?

> peer-disabled:cursor-not-allowed: Applies cursor-not-allowed (a cursor that shows as a crossed-out circle) to the element when the peer element (the related element with the peer class) is disabled. The peer-disabled: prefix allows the styling of elements based on the state of their "peer" elements.
> 
> peer-disabled:opacity-70: Sets the element’s opacity to 70% when the peer element is disabled, making it appear semi-transparent to indicate that it’s inactive or unavailable.

2024-11-04 08:23 UTC, TomlDev commented on libs/src/common/types/boolean-input-prop.ts
> +interface BooleanInputProp {
I don't understand why its called `Boolean...` when the value is `string` or `number`

2024-11-04 08:24 UTC, TomlDev commented on libs/src/common/types/single-input-prop.ts
> +  readOnly?: boolean;
The 3 types are nearly the same, what about a base type and derived types?

2024-11-04 08:28 UTC, TomlDev commented on apps/frontend/src/pages/UserSettings/Details/UserSettingsDetailsForm.tsx
> +  const { userDataFields, userDataMultiFields } = props;
I think you can move them down to this component since they are not used in the parent component and only passed as props.

2024-11-04 08:30 UTC, TomlDev commented on apps/frontend/src/pages/UserSettings/Details/UserSettingsDetailsPage.tsx
> +              onChange={() => {}}
Please make it optional instead of passing an empty function.

2024-11-04 08:55 UTC, TomlDev commented on apps/frontend/src/components/shared/BadgeField.tsx
> +    const newList = badges.filter((mp) => mp !== listItem);
mp?

2024-11-04 08:58 UTC, TomlDev requested changes
Some minor stuff

2024-11-04 11:51 UTC, maierdominik commented on apps/frontend/src/pages/UserSettings/Security/components/PasswordChangeForm.tsx
> +            className="block text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
I did not remember this change.

But it seems, that i wanted to unify the label styles. We use those 'peer'-names inside our label component:
![image](https://github.com/user-attachments/assets/2664f62a-33d5-4cc1-9e13-98a4990605b2)

2024-11-04 12:19 UTC, maierdominik commented on apps/frontend/src/components/shared/BadgeField.tsx
> +    const newList = badges.filter((mp) => mp !== listItem);
now called `str`

2024-11-04 12:20 UTC, maierdominik commented on libs/src/common/types/single-input-prop.ts
> +  readOnly?: boolean;
![image](https://github.com/user-attachments/assets/356c6717-868c-4f67-a11c-611fa0bf4cf5)

2024-11-04 12:20 UTC, maierdominik commented on libs/src/common/types/boolean-input-prop.ts
> +interface BooleanInputProp {
deprecated

2024-11-04 12:58 UTC, maierdominik commented on apps/frontend/src/pages/UserSettings/Details/UserSettingsDetailsPage.tsx
> +      { label: t('usersettings.details.name'), value: user?.name || '...' },
oh, habs jetzt schon in dem branch

2024-11-07 13:45 UTC, TomlDev commented on apps/frontend/src/components/shared/NotAvailable.tsx
> +const NotAvailable = <p className="italic">{t('common.not-available')}</p>;
Use `<span>` instead

> Choosing between `<div>`, `<span>`, and `<p>` depends on the intended purpose and semantic meaning of the HTML content. Here’s a breakdown of when to use each:
> 
> ### 1. **`<div>` (Division)**
> - **Purpose**: Used as a block-level container for grouping related content.
> - **Use Case**: When you need to group elements together without applying any semantic meaning.
> - **Characteristics**:
>   - Block-level element: Takes up the full width of its parent container.
>   - Commonly used for layout purposes, like sections or containers for styling.
> - **Examples**:
>   ```html
>   <div class="card">
>     <h2>Title</h2>
>     <p>Some content here.</p>
>   </div>
>   ```
> 
> **When to use**: Use `<div>` when you need a generic container to group elements for layout or styling without conveying any meaning about the content.
> 
> ### 2. **`<span>`**
> - **Purpose**: Used as an inline container for grouping small portions of text or elements.
> - **Use Case**: When you need to style a specific part of text or group inline elements without applying block-level formatting.
> - **Characteristics**:
>   - Inline element: Takes up only as much width as necessary.
>   - Does not start a new line, unlike block-level elements.
> - **Examples**:
>   ```html
>   <p>This is an <span class="highlight">important</span> word.</p>
>   ```
> 
> **When to use**: Use `<span>` when you need to apply styles or scripts to a part of text or inline content without affecting the surrounding flow.
> 
> ### 3. **`<p>` (Paragraph)**
> - **Purpose**: Represents a block of text as a paragraph.
> - **Use Case**: When you are marking up plain text content as a standalone paragraph.
> - **Characteristics**:
>   - Block-level element: Takes up the full width and adds vertical space before and after the paragraph.
>   - Adds semantic meaning to the content, indicating that it is a paragraph of text.
> - **Examples**:
>   ```html
>   <p>This is a standalone paragraph of text that explains an idea or provides information.</p>
>   ```
> 
> **When to use**: Use `<p>` when you have a block of text that represents a paragraph to convey semantic meaning to the browser and assistive technologies.
> 
> ### **Summary**
> - **Use `<div>`** for grouping and layout purposes, without semantic meaning.
> - **Use `<span>`** for applying styles or logic to small sections of text or inline content.
> - **Use `<p>`** for text content that should be marked as a paragraph, providing semantic meaning.
> 
> ### Example Scenario:
> If you are building an article, you would use:
> - `<div>` to structure the main sections of the article.
> - `<p>` to format paragraphs of text within those sections.
> - `<span>` to highlight or style specific words or inline elements within the paragraphs.
> 
> Understanding these distinctions helps maintain good HTML structure, enhances accessibility, and improves the maintainability of your code.

2024-11-07 13:49 UTC, TomlDev commented on apps/frontend/src/components/shared/NotAvailable.tsx
I think we should speak about the components name.
From the name it is not clear when to use this component, maybe we can improve that...

> A better name for this component could more explicitly reflect its purpose and use case. Here are some options:
> 
> 1. **PlaceholderText**: Suggests that this is a placeholder message displayed when content is unavailable.
> 2. **EmptyStateMessage**: Indicates that the component is used to show a message when data or content is missing.
> 3. **UnavailableMessage**: Clearly states that this message is used to indicate unavailable content.
> 4. **FallbackText**: Implies that this text is a fallback when there is no content to display.
> 5. **ContentUnavailable**: A descriptive name that signals that the component is shown when content is not available.
> 
> These names provide a clearer indication of the component's purpose when used in tables or cards.


My favorite at the moment is `FallbackText`, what do you think?

2024-11-07 14:05 UTC, TomlDev commented on apps/frontend/src/components/shared/FormField.tsx
> +        <FormItem className="items-center space-y-2">
I can't see the difference (I removed it and nothing changed in several locations)

2024-11-07 14:08 UTC, TomlDev requested changes
Only 3 last comments

2024-11-08 12:36 UTC, maierdominik commented on apps/frontend/src/components/shared/NotAvailable.tsx
> +const NotAvailable = <p className="italic">{t('common.not-available')}</p>;
thx

2024-11-08 12:48 UTC, maierdominik commented on apps/frontend/src/pages/UserSettings/Security/components/PasswordChangeForm.tsx
> +            className="block text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
We are now using our existing `<Label />` component.

2024-11-14 08:47 UTC, TomlDev commented on apps/frontend/src/components/layout/NativeAppHeader.tsx
> +      className="mr-2 flex min-h-[100px]"
In mobile thats too big, use `md:min-h-[100px]`
![grafik](https://github.com/user-attachments/assets/a5407166-7e52-48eb-93cc-d38f9ac5cd69)

2024-11-14 08:50 UTC, TomlDev commented on apps/frontend/src/pages/UserSettings/Mails/UserSettingsMailsPage.tsx
> +      data-testid={`test-id-login-page-${fieldName}-input`}
I think this should be removed, what do you think? Looks like copy/paste fault

2024-11-14 08:52 UTC, TomlDev commented on apps/frontend/src/pages/UserSettings/Details/UserSettingsDetailsPage.tsx
> +        description=""
![grafik](https://github.com/user-attachments/assets/8712b6cd-a318-4ce8-969f-01dc56a77af2)

2024-11-14 08:53 UTC, TomlDev commented on apps/frontend/src/pages/UserSettings/Security/components/PasswordChangeForm.tsx
> +            className="block text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
What about using the `<Label>` component here, too?

2024-11-14 08:53 UTC, TomlDev commented on apps/frontend/src/pages/UserSettings/Security/components/PasswordChangeForm.tsx
> +            className="block text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
What about using the `<Label>` component here, too?

2024-11-14 08:54 UTC, TomlDev commented on apps/frontend/src/components/shared/BadgeFormField.tsx
> +    currentValue: string[],
currentBadges

2024-11-14 08:55 UTC, TomlDev commented on apps/frontend/src/components/shared/BadgeFormField.tsx
> +              {badges?.map((listItem) => (
Instead of `listItem` better something like `badge`?

2024-11-14 08:55 UTC, TomlDev commented on apps/frontend/src/components/shared/BadgeFormField.tsx
> +                  key={`badge-${listItem}`}
Can you know for sure that they are unique so they should be used as key here?

2024-11-14 08:57 UTC, TomlDev commented on apps/frontend/src/components/shared/BadgeFormField.tsx
> +    if (!currentValue || !removeLabel || !handleChange) return;
Can currentValue be false? I don't know but from my feeling it could be an empty array so you maybe want to check for that

2024-11-14 08:58 UTC, TomlDev commented on apps/frontend/src/components/shared/BadgeFormField.tsx
> +    handleChange?: (updatedValue: string[]) => void,
I this context I would call the function `updateBadges` and its parameter should be plural

2024-11-14 08:59 UTC, TomlDev commented on apps/frontend/src/components/shared/BadgeFormField.tsx
> +    removeLabel: string,
`removeLabel` is not the correct term, since it's a request 'remove label' or a boolean 'remove label = true'

2024-11-14 09:00 UTC, TomlDev commented on apps/frontend/src/components/shared/BadgeFormField.tsx
> +  const handleAddBadge = (
Everything that applies to `handleRemoveBadge` applies also here

2024-11-14 09:01 UTC, TomlDev commented on apps/frontend/src/components/shared/BadgeFormField.tsx
> +    if (alreadyExists !== -1) {
Why so complex with index search? I am sure you will find a better function that directly returns a boolean!
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

2024-11-14 09:02 UTC, TomlDev requested changes
Still some small findings

2024-11-14 14:40 UTC, maierdominik commented on apps/frontend/src/pages/UserSettings/Security/components/PasswordChangeForm.tsx
> +            className="block text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
I don't know how i could have been that blind 🙈

2024-11-14 14:45 UTC, maierdominik commented on apps/frontend/src/pages/UserSettings/Details/UserSettingsDetailsPage.tsx
> +        description=""
<img width="531" alt="image" src="https://github.com/user-attachments/assets/462ba79a-2a86-46c7-a384-f0540a6f96c2">

<img width="460" alt="image" src="https://github.com/user-attachments/assets/e407e61c-a317-4409-adfd-c00aa12a0830">

<img width="460" alt="image" src="https://github.com/user-attachments/assets/e234340a-8f79-4306-b248-3c67635eea73">

2024-11-15 12:42 UTC, TomlDev commented on apps/frontend/src/components/shared/BadgeFormField.tsx
> +    badgeStrToAdd: string,
Please don't use an abbreviation in this case I find it's hard to read/understand.
It was okay for me with `badgeLabelToAdd`

2024-11-15 12:46 UTC, TomlDev approved these changes

2024-11-19 10:39 UTC, merged