Filter for current school when fetching users or groups
edulution-io/edulution-ui pull request #189
Opened 2024-10-15 16:25 UTC by Maddi02

This PR introduces a feature that restricts users' access to specific classes and printers based on their assigned school. The changes ensure that users can only view and interact with resources that are available to their associated school.

### Changed
- Store users by school in cache
- Store groups by school in cache
- Store schools in cache
- Global admin can fetch all users/groups
- Fix group fetch 
  - Decrease the console errors
  - Retry on failed fetches
  - Don't block API start up
 

OLD:
> It is important to clarify if handling multiple school assignments per teacher is a relevant use case, as this scenario is not supported in the current implementation.

2024-10-22 11:14 UTC, TomlDev requested changes
Looks good 👍🏽

2024-10-24 12:26 UTC, TomlDev requested changes
Some changes have to be reverted, others should be added 👍🏽

2024-10-29 09:00 UTC, TomlDev commented on apps/api/src/groups/groups.service.ts
> +      return await GroupsService.makeAuthorizedRequest<Record<string, LDAPUser[]>>(HttpMethods.GET, 'users', token);
I think this did not change.
When you query keycloak it does return an array of users and not an object with `[key]: LDAPUser[]`

2024-10-29 09:04 UTC, TomlDev commented on apps/api/src/users/users.service.ts
> +    return usersBySchool;
This gives an error when I search for a user in create conference:
![grafik](https://github.com/user-attachments/assets/6cd618ca-28b1-4234-80fd-8667fb921db0)

2024-10-29 09:07 UTC, TomlDev commented on libs/src/groups/types/ldapUserAttributes.ts
> +  school: string[];
When I checked the `fetchAllUsers` response the LDAPUser was only this, are you sure that these attributes need an adjustment?
```
  {
    "id": "527b810e-19ef-434e-bf2c-1e274e57be32",
    "username": "johnsomi",
    "firstName": "Min-Jun",
    "lastName": "Johnson",
    "email": "johnsomi@lm.schulung.multi.schule",
    "emailVerified": true,
    "createdTimestamp": 1729860502977,
    "enabled": true,
    "federationLink": "30f7a925-f6c4-424c-bf83-88ea3acf68d3"
  },

2024-10-29 09:24 UTC, TomlDev commented on apps/api/src/lmnApi/lmnApi.service.ts
Alright, yes if you don't find a solution we can try to debug it together 👍🏽

2024-11-07 11:53 UTC, TomlDev commented on libs/src/groups/types/ldapUserAttributes.ts
> +  school: string[];
`school` must be optional since it's not always present

2024-11-07 12:13 UTC, TomlDev commented on apps/api/src/users/users.service.ts
> +  async findAllCachedUsers(token: string, school: string): Promise<Record<string, LDAPUser[]>> {
Your changes are valid and OK 👍🏽 

But I think we have an opportunity here to improve it further:
Redis is used as a key/value database and therefore we can now divide the users entry by schools.

Before we had one BIG entry for all users but now we can have a smaller entry for each school.
So what we have to do is:

1. Fetch all users (Keycloak natively does not support filtering for example for `attributes.school`)
2. Sort the users by schools
3. Store them in Redis by school
```
const ALL_USERS_CACHE_KEY = 'allUsers-';  // this should be in the shared-lib
usersBySchool.forEach(school) -> 
await this.cacheManager.set(ALL_USERS_CACHE_KEY + school, usersBySchool[school], DEFAULT_CACHE_TTL_MS);
```
4. When a user fetches the users it sends his school 
```
const cachedUsers = await this.cacheManager.get<Record<string, LDAPUser[]>>(ALL_USERS_CACHE_KEY + school);
```

2024-11-07 12:15 UTC, TomlDev requested changes
Some refactorings regarding the Redis store 👍🏽 
+ the tests are failing

2025-02-25 09:40 UTC, michidold requested changes
Found some stuff. One major issue, default school groups are not found and in classmgmt the fetch of all groups takes very long. Seems its related to the first issue

2025-02-25 09:40 UTC, michidold commented on apps/api/src/groups/groups.service.ts
I have the issue that the default school groups are not found. They follow their own pattern:
![grafik](https://github.com/user-attachments/assets/7048fc5c-1dbd-405e-bec9-fbe7c3e1d9a9)

2025-02-25 09:40 UTC, michidold commented on apps/api/src/groups/groups.service.ts
> +  }
Since they are used at one place, I think it makes sense to format it here as it will be needed -> `.replace('/s_', '')`

2025-02-25 10:32 UTC, TomlDev commented on apps/api/src/groups/groups.service.ts
> +  }
I don't think that it makes sense to manipulate the original data since we have to use the full name in places.
For example when sending the request to join a class, etc.

2025-02-25 14:29 UTC, TomlDev commented on apps/api/src/groups/groups.service.ts
Really good catch, thank you.
I fixed it now.

For the long loading: As discussed today this seems to be related to LMN changes.

2025-02-26 12:28 UTC, TomlDev approved these changes
Very good and professional 👍🏽

2025-02-26 12:31 UTC, merged