NIEDUUI-359: Implement-the-hand-out-feature-of-LMN
edulution-io/edulution-ui pull request #197
Opened 2024-10-17 18:16 UTC by Maddi02

### Description

This merge request introduces a feature that allows teachers to collect files from students. Teachers can choose either to **move** files from the student directory or simply **copy** them.

### Important for Review

- **500 Error with Copy Command**: The `COPY` command currently triggers a 500 error, even though it successfully copies the files. This issue is being investigated in collaboration with Arnaud (see Issue [#217])
  
- **No Exam Mode Functionality**: This merge request does not include functionality for Exam Mode, as several essential features do not function correctly in this environment. Specifically, user data cannot currently be fetched from Keycloak (see Issue [#219]

2024-10-31 09:31 UTC, TomlDev commented on apps/api/src/filesharing/filesharing.controller.ts
> +    );
```
  @Post(FileSharingApiEndpoints.COLLECT)
  async collectFiles(
    @Body() body: { collectFileRequestDTO: CollectFileRequestDTO[] },
    @Query('type') type: LmnApiCollectOperations,
    @Query('userRole') userRole: string,
    @GetCurrentUsername() username: string,
  ) {
    const { collectFileRequestDTO } = body;
    return this.filesharingService.collectFiles(
      username,
      collectFileRequestDTO,
      userRole,
      type,
    );
  }

2024-10-31 09:41 UTC, TomlDev commented on apps/api/src/filesharing/filesharing.service.ts
> +        }
The `collectFiles` fn has many catch blocks that only log to the console. Does that make sense?
If it fails to create the initial folder, does it make sense to continue with the later operations?

2024-10-31 09:46 UTC, TomlDev commented on apps/api/src/filesharing/filesharing.service.ts
> +    const sanitizedDestinationPath = destinationPath.replace(`${FILE_PATHS.COLLECT}/`, '');
I think since the function uses this hardcoded `FILE_PATHS.COLLECT` replace I wouldn't give it a general name like `createFolderIfNotExists`

2024-10-31 09:52 UTC, TomlDev commented on apps/api/src/filesharing/filesharing.service.ts
> +    const sanitizedDestinationPath = destinationPath.replace(/\u202F/g, ' ');
Why is this character in the path?

2024-10-31 09:53 UTC, TomlDev commented on apps/api/src/filesharing/filesharing.service.ts
> +  private async copyFile(client: AxiosInstance, originPath: string, destinationPath: string) {
The linter says "ESLint: Expected 'this' to be used by class async method 'copyFile'.(@typescript-eslint/class-methods-use-this)"

2024-10-31 09:55 UTC, TomlDev commented on apps/api/src/filesharing/filesharing.service.ts
> +  cuteCollectedItems = async (username: string, originPath: string, newPath: string): Promise<WebdavStatusReplay> => {
to cut /= cute

2024-10-31 09:59 UTC, TomlDev commented on apps/frontend/src/components/ui/Dialog.tsx
> +  layout?: 'one-column' | 'two-column';
Since it's used multiple times, please move it to the shared lib.
Also normally I would suggest to use an enum instead then. Or as we now do, use a const

2024-10-31 10:00 UTC, TomlDev commented on apps/frontend/src/locales/de/translation.json
> +    "enrolPageDescription": "Wählen Sie die Klassen und Projekte aus, für die Sie sich einschreiben möchten, indem Sie die Checkboxen aktivieren.",
du

2024-10-31 10:00 UTC, TomlDev commented on apps/frontend/src/locales/de/translation.json
> +    "copyOrCut": "Möchten Sie die Dateien ausschneiden oder kopieren?"
du

2024-10-31 10:01 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/LessonPage/useLessonStore.ts
> +import LmnAp from '@libs/lmnApi/types/lmnApiCollectOperations';
Better import as `LmnApiCollectOperations`

2024-10-31 10:04 UTC, TomlDev commented on libs/src/classManagement/types/store/lessonStore.ts
> +import LmnAp from '@libs/lmnApi/types/lmnApiCollectOperations';
LmnApiCollectOperations

2024-10-31 10:41 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/components/Dialogs/CollectFilesDialog.tsx
Something to the "share" dialog:
![image](https://github.com/user-attachments/assets/186c5c45-81ea-4742-825b-2c6c8e6d9982)

![image](https://github.com/user-attachments/assets/536187c9-6246-43c2-a171-88d967968ee6)

2024-10-31 10:49 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/components/Dialogs/CollectFilesDialog.tsx
> +        </Button>
Currently when you click "collect" it loads, then it finish loading but there is no acknowledgment to the user if it worked. There should be a toaster

2024-10-31 10:49 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/components/Dialogs/CollectFilesDialog.tsx
> +        </DropdownMenuSH>
![image](https://github.com/user-attachments/assets/1db04f81-4c63-4c69-9433-11707f23db38)
![image](https://github.com/user-attachments/assets/b6a9f2df-df66-4f93-b9fe-8395376c3996)

2024-10-31 10:51 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/components/Dialogs/CollectFilesDialog.tsx
There is something going wrong when switching the dialogs. Either it should show a loading icon or be empty until data is loaded

https://github.com/user-attachments/assets/144d428e-96ea-45b5-8cf6-404306de31d6

2024-10-31 11:46 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/components/Dialogs/CollectFilesDialog.tsx
> +  const [selectedOption, setSelectedOption] = useState(options[0]);
There is normally no need to handle a state locally in a component AND in the store 
For example you could use 
- an array like yours with `id: LmnApiCollectOperations`:
```
const selectedOption = options.find(o => o.id === useLessonStore().selectedCollectionType)
```

- an object
```
const options = {
  [LmnApiCollectOperations.CUT]: {
      label: t('classmanagement.collectAndCut'),
      icon: <FaCut />,
  }
}
```

and access it with 
`const selectedOption =  options[useLessonStore().selectedCollectionType]`

2024-10-31 12:15 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/components/Dialogs/CollectFilesDialog.tsx
> +    <div className="h-[120px] justify-between py-2">
I don't think that this belongs into the footer.
It should be part of the body because it's the content of the dialog.
The AI:

> In a React dialog component, the **footer** serves as a designated area at the bottom of the dialog for user actions or additional information. Common uses include:
> 
> 1. **Action Buttons**: Frequently, the footer contains buttons for actions such as "Save," "Cancel," or "Confirm." These buttons enable users to proceed with or dismiss the dialog's purpose without additional navigation.
> 2. **Status Information**: A footer can also display supplementary information, such as form submission status, validation messages, or loading indicators, helping users understand the dialog's state or any required next steps.
> 3. **Additional Context**: Some footers offer helpful context or tips related to the dialog content, making it easier for users to make informed decisions or understand any dependencies.
> 
> In general, a footer helps establish a clear layout and supports better usability by keeping actions accessible and organized, especially in dialogs with complex or multi-step content. It also reinforces visual hierarchy by clearly separating actions from the main content.

2024-10-31 12:16 UTC, TomlDev commented on apps/frontend/src/components/ui/DropdownMenuSH.tsx
> +  <DropdownMenuPrimitive.Content
Why was the portal removed?

2024-10-31 12:16 UTC, TomlDev requested changes
👍🏽

2025-01-17 09:05 UTC, TomlDev commented on apps/api/src/filesharing/filesharing.service.ts
> +      Logger.log(error); // TODO: Replace this with a custom exception. Issue #217
TODO

2025-02-26 10:52 UTC, TomlDev requested changes
Please have a look at the comments.
I fixed the problem that the lesson screen did not restore the users when the app was switched.

2025-02-26 10:52 UTC, TomlDev commented on apps/api/src/filesharing/filesharing.service.ts
> +        success: response.success,
This transformer does not seem to be necessary

2025-02-26 10:52 UTC, TomlDev commented on apps/api/src/lmnApi/lmnApi.service.ts
> +  }
This seems to be a utility function -> shared-lib

2025-02-26 10:52 UTC, TomlDev commented on apps/frontend/src/components/ui/AdaptiveDialog.tsx
Can you explain the undocumented changes in this file?
Please also add screenshots or a video to demonstrate it

2025-02-26 10:52 UTC, TomlDev commented on apps/frontend/src/components/ui/Dialog.tsx
Can you provide some screenshots for this unrelated and undocumented change?

2025-02-26 10:52 UTC, TomlDev commented on apps/frontend/src/components/ui/DropdownMenuSH.tsx
I tried to understand where these changes are used, but couldn't find it.

2025-02-26 10:52 UTC, TomlDev commented on apps/frontend/src/components/ui/DropdownMenuSH.tsx
> +  </DropdownMenuPrimitive.Trigger>
I am unsure what the goal of this is. Normally I would expect that anything can be passed as Trigger, including icons and labels so there is no necessity to add this logic here

2025-02-26 10:52 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/LessonPage/useLessonStore.ts
> +          toast.success(t('classmanagement.filesShared'));
This will show the success message in every case, also in the catch (error) case. Move it inside the try block

2025-02-26 10:52 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/LessonPage/useLessonStore.ts
> +          toast.success(t('classmanagement.filesCollected'));
Same as above

2025-02-26 10:52 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/components/Dialogs/CollectFilesDialog.tsx
![grafik](https://github.com/user-attachments/assets/f3382008-9b3c-4e1c-8909-7bec33458b1e)

2025-02-26 10:52 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/components/Dialogs/CollectFilesDialog.tsx
> +      id: LmnApiCollectOperationsType;
This seems strange, either use it as key in an object or as id in an array

2025-02-26 10:52 UTC, TomlDev commented on apps/frontend/src/pages/FileSharing/dialog/DialogBodys/MoveContentDialogWrapper.tsx
> +const MoveContentDialogWrapper: React.FC<Omit<MoveContentDialogProps, 'pathToFetch'>> = (props) => {
Instead of `wrapper` which has virtually no meaning please find a better, descriptive name.
For what is it specially used? Or in which place?

2025-02-26 10:52 UTC, TomlDev commented on apps/frontend/src/pages/FileSharing/table/FileSharingTable.tsx
> +      columns={FileSharingTableColumns()}
If this is a function it violates some spelling rules

2025-02-26 10:52 UTC, TomlDev commented on apps/frontend/src/pages/FileSharing/dialog/DialogBodys/MoveContentDialogBody.tsx
Please check if you can adapt some of the changes the AI proposes:

> Below is a **refactored** version of the same component. It preserves all **logic** and **behavior** but makes the code slightly more readable and consistent:
> 
> - **Unifies** the `useEffect` logic for fetching data (fewer nested `if`s).  
> - **Slightly simplifies** the row‑selection handler.  
> - **Clarifies** variable names in `onFilenameClick`.  
> - **Adjusts** minor stylistic details in `getHiddenSegments`.  
> 
> Everything else (function signatures, data flow, etc.) remains **unchanged**.
> 
> ```tsx
> /*
>  * LICENSE
>  *
>  * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by
>  * the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
>  *
>  * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
>  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
>  *
>  * You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.
>  */
> 
> import { DirectoryFileDTO } from '@libs/filesharing/types/directoryFileDTO';
> import React, { useEffect, useState } from 'react';
> import { useTranslation } from 'react-i18next';
> import useFileSharingStore from '@/pages/FileSharing/useFileSharingStore';
> import DirectoryBreadcrumb from '@/pages/FileSharing/breadcrumb/DirectoryBreadcrumb';
> import useFileSharingDialogStore from '@/pages/FileSharing/dialog/useFileSharingDialogStore';
> import ScrollableTable from '@/components/ui/Table/ScrollableTable';
> import APPS from '@libs/appconfig/constants/apps';
> import { FileSharingTableColumns } from '@/pages/FileSharing/table/FileSharingTableColumns';
> import { ColumnDef, OnChangeFn, RowSelectionState } from '@tanstack/react-table';
> import FILESHARING_TABLE_COLUM_NAMES from '@libs/filesharing/constants/filesharingTableColumNames';
> import MoveContentDialogBodyProps from '@libs/filesharing/types/moveContentDialogProps';
> import ContentType from '@libs/filesharing/types/contentType';
> import LoadingIndicator from '@/components/shared/LoadingIndicator';
> import useLmnApiStore from '@/store/useLmnApiStore';
> 
> const MoveContentDialogBody: React.FC<MoveContentDialogBodyProps> = ({
>   showAllFiles = false,
>   pathToFetch,
>   showSelectedFile = true,
>   showHome = true,
>   fileType,
> }) => {
>   const { t } = useTranslation();
>   const [currentPath, setCurrentPath] = useState(pathToFetch || '');
> 
>   const { user } = useLmnApiStore();
> 
>   const {
>     setMoveOrCopyItemToPath,
>     moveOrCopyItemToPath,
>   } = useFileSharingDialogStore();
> 
>   const {
>     fetchDialogDirs,
>     fetchDialogFiles,
>     dialogShownDirs,
>     dialogShownFiles,
>     isLoading,
>   } = useFileSharingStore();
> 
>   // Decide which fetch function to use based on fileType
>   const fetchMechanism =
>     fileType === ContentType.DIRECTORY
>       ? fetchDialogDirs
>       : fetchDialogFiles;
> 
>   // Decide which files/dirs to show based on fileType
>   const files =
>     fileType === ContentType.DIRECTORY
>       ? dialogShownDirs
>       : dialogShownFiles;
> 
>   // Handle row selection in the ScrollableTable
>   const handleRowSelectionChange: OnChangeFn<RowSelectionState> = (updaterOrValue) => {
>     const selectionValue =
>       typeof updaterOrValue === 'function' ? updaterOrValue({}) : updaterOrValue;
> 
>     const selectedItems = Object.entries(selectionValue)
>       .filter(([_, isSelected]) => isSelected)
>       .map(([rowId]) => files.find((file) => file.filename === rowId))
>       .filter(Boolean) as DirectoryFileDTO[];
> 
>     // Only care about the first selected item
>     setMoveOrCopyItemToPath(selectedItems[0]);
>   };
> 
>   // Clicking a directory row should navigate into that directory
>   const onFilenameClick = (item: DirectoryFileDTO) => {
>     if (item.type === ContentType.DIRECTORY) {
>       let newPath = currentPath;
>       if (!newPath.endsWith('/')) {
>         newPath += '/';
>       }
>       if (newPath === '/') {
>         newPath += item.filename
>           .replace('/webdav/', '')
>           .replace(`server/${user?.school}/`, '');
>       } else {
>         newPath += item.basename;
>       }
>       setCurrentPath(newPath);
>     }
>   };
> 
>   // Fetch logic on mount/update
>   useEffect(() => {
>     // If we don't want to show all files, simply fetch currentPath
>     if (!showAllFiles) {
>       void fetchMechanism(currentPath);
>       return;
>     }
> 
>     // showAllFiles is true
>     // 1) If pathToFetch is undefined => fetch currentPath
>     if (!pathToFetch) {
>       void fetchMechanism(currentPath);
>       return;
>     }
> 
>     // 2) pathToFetch is defined
>     // if currentPath includes pathToFetch => fetch currentPath
>     // else => fetch pathToFetch
>     if (currentPath.includes(pathToFetch)) {
>       void fetchMechanism(currentPath);
>     } else {
>       void fetchMechanism(pathToFetch);
>     }
> 
>     // eslint-disable-next-line react-hooks/exhaustive-deps
>   }, [currentPath]); // Keep original dependency to match the existing logic
> 
>   // Allows the DirectoryBreadcrumb to navigate "up" or to specific subpaths
>   const handleBreadcrumbNavigate = (path: string) => {
>     const newPath = path.replace('webdav/', '');
>     setCurrentPath(newPath);
>   };
> 
>   // Gather hidden segments from pathToFetch
>   const getHiddenSegments = (): string[] => {
>     if (!pathToFetch) return [];
>     const segments = pathToFetch.split('/');
>     // The original code tries to find the last segment index
>     const index = segments.findIndex(
>       (segment) => segment === segments.at(segments.length - 1)
>     );
>     return index > -1 ? segments.slice(0, index) : [];
>   };
> 
>   // Footer element: show selected item or a message to select a file
>   const footer = (
>     <div className="bottom-0 justify-end bg-gray-100 p-4 text-sm text-foreground">
>       {moveOrCopyItemToPath?.basename && showSelectedFile ? (
>         <p className="bg-gray-100">
>           {t('moveItemDialog.selectedItem')}: {moveOrCopyItemToPath.basename}
>         </p>
>       ) : (
>         <p className="bg-gray-100">
>           <span>{t('filesharing.selectFile')}</span>
>         </p>
>       )}
>     </div>
>   );
> 
>   // Only show a single "filename with selection checkbox" column
>   const visibleColumns = [FILESHARING_TABLE_COLUM_NAMES.SELECT_FILENAME];
>   const columns: ColumnDef<DirectoryFileDTO>[] = FileSharingTableColumns(
>     visibleColumns,
>     onFilenameClick
>   );
> 
>   return (
>     <div className="h-[60vh] flex-col overflow-auto text-background scrollbar-thin">
>       <LoadingIndicator isOpen={isLoading} />
>       <div className="pb-2">
>         <DirectoryBreadcrumb
>           path={currentPath}
>           onNavigate={handleBreadcrumbNavigate}
>           showHome={showHome}
>           hiddenSegments={getHiddenSegments()}
>           showTitle={false}
>         />
>       </div>
>       {!isLoading && (
>         <div className="overflow-auto">
>           <ScrollableTable
>             columns={columns}
>             data={files}
>             selectedRows={
>               moveOrCopyItemToPath
>                 ? { [moveOrCopyItemToPath.filename]: true }
>                 : {}
>             }
>             onRowSelectionChange={handleRowSelectionChange}
>             applicationName={APPS.FILE_SHARING}
>             getRowId={(row) => row.filename}
>             showHeader={false}
>             textColorClass="text-background"
>             showSelectedCount={false}
>             footer={footer}
>             filterKey="select-filename"
>             filterPlaceHolderText="filesharing.filterPla [...]

2025-02-26 10:52 UTC, TomlDev commented on apps/frontend/src/pages/FileSharing/table/FileSharingTableColumns.tsx
> +        };
Ai proposes:

> Below is one way to apply **early returns** to simplify the control flow. The logic remains the same, but it’s a bit clearer and easier to follow:
> 
> ```ts
> const handleFilenameClick = async () => {
>   // If an onFilenameClick handler was provided, just call it and exit.
>   if (onFilenameClick) {
>     onFilenameClick(row.original);
>     return;
>   }
> 
>   // If clicking is currently disabled, do nothing.
>   if (isCurrentlyDisabled) {
>     return;
>   }
> 
>   // Otherwise, proceed with the default behavior.
>   setShowEditor(false);
>   setPublicDownloadLink('');
> 
>   if (row.original.type === ContentType.DIRECTORY) {
>     setCurrentlyEditingFile(null);
>     searchParams.set('path', getPathWithoutWebdav(row.original.filename));
>     setSearchParams(searchParams);
>   } else {
>     // This needs `async/await`, so keep the function `async`.
>     await resetCurrentlyEditingFile(row.original);
>   }
> };
> ```
> 
> ### What Changed
> 
> 1. **Early Return**  
>    - We immediately return after calling `onFilenameClick` when `onFilenameClick` exists, so no else-block is required.
>    - If `isCurrentlyDisabled`, we return immediately as well, short-circuiting the rest.
> 
> 2. **Same Logic, Clearer Flow**  
>    - The core actions and conditions are unaltered, just reorganized. This makes it easier to see in which scenario each piece of code runs.

2025-02-26 10:52 UTC, TomlDev commented on apps/frontend/src/pages/FileSharing/table/FileSharingTableColumns.tsx
> +        };
Please extract this method to the top of the file, outside of the array

2025-02-26 10:52 UTC, TomlDev commented on apps/frontend/src/pages/FileSharing/useFileSharingStore.ts
> +  dialogShownFiles: DirectoryFileDTO[];
Please move everything related to the dialog to it's own store.

2025-02-26 10:52 UTC, TomlDev commented on libs/src/classManagement/types/store/lessonStore.ts
> +  collectionType: LmnApiCollectOperationsType;
I think this should be moved to another store. From the place where it is defined and its name it's intent is totally unclear.
The minimum would be to rename it to something way more straight forward. `collectDialogCurrentlySelectedCollectionOperation` or something, I don't know

2025-02-26 10:52 UTC, TomlDev commented on libs/src/filesharing/utils/getCurrentTimestamp.ts
> +const getCurrentTimestamp = (): string =>
Please add an example as comment so we can see what kind of timestamp this produces

2025-02-26 10:52 UTC, TomlDev commented on apps/frontend/src/components/ui/AdaptiveDialog.tsx
> +        </VisuallyHidden>
Why this?

2025-02-26 14:46 UTC, Maddi02 commented on apps/api/src/filesharing/filesharing.service.ts
> +      Logger.error(error);
There is no reason. Changed it to a `CustomHttpException`

2025-02-26 17:10 UTC, Maddi02 commented on apps/frontend/src/components/ui/AdaptiveDialog.tsx
There is no good reason to change this component. I guess it was some stuff that should have been fixed some time ago. However, these changes are no longer needed.

2025-02-26 17:11 UTC, Maddi02 commented on apps/frontend/src/pages/ClassManagement/components/Dialogs/CollectFilesDialog.tsx
Should be fixed

![image](https://github.com/user-attachments/assets/b164172f-5a73-4fab-a600-d28d99acc009)

2025-02-26 17:30 UTC, Maddi02 commented on libs/src/filesharing/utils/getCurrentTimestamp.ts
> +const getCurrentTimestamp = (): string =>
`LOG [26-02-2025_18-30-03] currentTimeStamp`

2025-02-27 09:24 UTC, Maddi02 commented on apps/frontend/src/pages/ClassManagement/components/Dialogs/CollectFilesDialog.tsx
<img width="421" alt="image" src="https://github.com/user-attachments/assets/7ccbd337-20a2-4ad1-ab18-9073ed96935e" />

2025-02-27 12:01 UTC, Maddi02 commented
This PR contains the solution to #538. Due to the fact that moving files like `03+-+Data+Models+and+Query+Languages.pdf`to another folder does not work.

2025-02-27 13:19 UTC, TomlDev commented on apps/api/src/filesharing/filesharing.service.ts
> +  /* eslint-disable no-await-in-loop, no-restricted-syntax */
Okay :D I meant to refactor so no eslint rules must be disabled.
Something like this:
```
/* eslint-disable no-await-in-loop */ // <-- remove this and see new approach
async duplicateFile(username: string, duplicateFile: DuplicateFileRequestDto): Promise<WebdavStatusResponse> {
  const client = await this.getClient(username);

  await Promise.all(
    duplicateFile.destinationFilePaths.map(async (destinationPath) => {
      const pathUpToTransferFolder = FilesharingService.getPathUntilFolder(destinationPath, FILE_PATHS.TRANSFER);
      const pathUpToTeacherFolder = FilesharingService.getPathUntilFolder(destinationPath, username);

      const userFolderExists = await this.checkIfFileOrFolderExists(
        username,
        pathUpToTransferFolder,
        username,
        ContentType.DIRECTORY,
      );

      if (!userFolderExists) {
        await this.createFolder(username, pathUpToTransferFolder, username);

        // If we just created the user folder, then check/create the collect folder too.
        const collectFolderExists = await this.checkIfFileOrFolderExists(
          username,
          pathUpToTeacherFolder,
          FILE_PATHS.COLLECT,
          ContentType.DIRECTORY,
        );
        if (!collectFolderExists) {
          await this.createFolder(username, pathUpToTeacherFolder, FILE_PATHS.COLLECT);
        }
      }

      await FilesharingService.copyFile(client, duplicateFile.originFilePath, destinationPath);
    }),
  );

  return { success: true, status: HttpStatus.OK };
}

2025-02-27 13:19 UTC, TomlDev commented on apps/api/src/filesharing/filesharing.service.ts
> +        success: response.success,
This is unchanged

2025-02-27 13:26 UTC, TomlDev commented on libs/src/common/utils/convertWindowsToUnixPath.ts
I would move this to filesharing domain

2025-02-27 13:30 UTC, TomlDev commented on libs/src/filesharing/utils/getCurrentTimestamp.ts
> +const getCurrentTimestamp = (): string =>
Haha sorry, I meant in the code. As annotation so you can see it when you hover the function 👍🏽

2025-02-27 14:00 UTC, Maddi02 commented on apps/api/src/filesharing/filesharing.service.ts
> +        success: response.success,
i could reflect it

<img width="520" alt="image" src="https://github.com/user-attachments/assets/b387fea9-290d-4fac-aa7b-9829facf08d7" />

2025-02-28 09:04 UTC, TomlDev commented on apps/api/src/filesharing/filesharing.service.ts
> +    if (!folderAlreadyExistis) {
Use early return instead

2025-02-28 09:05 UTC, TomlDev approved these changes
@michidold please have a 2nd look 👍🏽

2025-03-11 13:27 UTC, Maddi02 commented
After some discussion on how to display the file-sharing progress, I’d like to show you a possible approach. Could you please give me some feedback?

<img width="442" alt="image" src="https://github.com/user-attachments/assets/e0aecea5-857b-47dd-8e57-b0a9f1eeaa69" />

2025-03-12 09:21 UTC, Maddi02 commented
Okay, I guess I won't add any extra features in this brach. Anyway its way too big. Added a retry mechanism if the share failed on puporse. 

Feel free to have a look.

https://github.com/user-attachments/assets/0a565fe7-07ba-4219-ad8f-d9bdd432b52c

2025-03-13 07:16 UTC, michidold commented on apps/api/src/filesharing/filesharing.service.ts
> +      await FilesharingService.copyFile(client, duplicateFile.originFilePath, destinationPath);
Ok, I was not precise, please rework every function in this file

2025-03-13 07:23 UTC, michidold commented on apps/frontend/src/locales/de/translation.json
> +    "collectAndCopy": "Kopieren",
They are still in place.

2025-03-13 08:15 UTC, michidold commented on apps/frontend/src/pages/FileSharing/table/FileSharingTableColumns.tsx
> +      },
Can you rework the others as well? There are more `function Cell` and `function Header ` declarations

2025-03-13 13:26 UTC, michidold requested changes
Had some findings, among other things the queue implementation needs to be refactored.

2025-03-13 17:31 UTC, Maddi02 commented on apps/api/src/filesharing/filesharing.service.ts
> +      await FilesharingService.copyFile(client, duplicateFile.originFilePath, destinationPath);
"I’ve changed every function to the async ab() {} syntax, except for uploadFile, which remains an arrow function to preserve its this binding for the OnlyOffice callback.

2025-03-13 18:10 UTC, Maddi02 commented on apps/api/src/filesharing/filesharingQueueProcessor.ts
> +    }
Now each file share is its own job in the queue. 


https://github.com/user-attachments/assets/0a2bfb2f-5060-45d8-957c-f8b5cee562f6

2025-03-14 08:50 UTC, michidold approved these changes
Looks good.

2025-03-14 10:54 UTC, TomlDev requested changes
See my comments

2025-03-14 10:54 UTC, TomlDev commented on apps/api/src/filesharing/filesharingQueueProcessor.ts
> Consumer vs. Processor
> 
>     Consumer is a common term in pub/sub or messaging systems (e.g., Kafka or RabbitMQ).
>     Processor is a bit more Bull-specific. It suggests that the class/function is responsible for processing the job’s logic rather than simply consuming messages in a generic sense.

I would rename the `FilesharingQueueProcessor` to `FilesharingConsumer` to use the naming that is widely used for this technology. I would not rely on this specific library that we use. It makes it clearer for outside developers.

(and the file to filesharing.consumer.ts because of our naming convention)

2025-03-14 10:54 UTC, TomlDev commented on apps/api/src/filesharing/filesharingQueueProcessor.ts
> +    }
This should be part of the file sharing service

```
// filesharing.service.ts
async ensureFolderExists(username: string, basePath: string, folderName: string) {
  const exists = await this.checkIfFileOrFolderExists(
    username,
    basePath,
    folderName,
    ContentType.DIRECTORY,
  );
  if (!exists) {
    await this.createFolder(username, basePath, folderName);
  }
}
```

Then here:
```
await this.fileSharingService.ensureFolderExists(username, pathUpToTransferFolder, username);
await this.fileSharingService.ensureFolderExists(username, pathUpToTeacherFolder, FILE_PATHS.COLLECT);

2025-03-14 10:54 UTC, TomlDev commented on apps/api/src/filesharing/filesharingQueueProcessor.ts
> +      case QUEUE_NAMES.DUPLICATE_FILE_QUEUE:
Is this a queue name or a job name?

2025-03-14 10:54 UTC, TomlDev commented on apps/frontend/src/components/ui/Table/ScrollableTable.tsx
> +  textColorClass = 'text-muted-foreground',
Classname

2025-03-14 10:54 UTC, TomlDev commented on apps/frontend/src/components/ui/Table/ScrollableTable.tsx
> +      {footer && <div className="max-w-[42vh] overflow-hidden text-ellipsis whitespace-nowrap">{footer}</div>}
Why the max width? What is with wider dialogs? Can you share a screenshot of this in use?

2025-03-14 10:54 UTC, TomlDev commented on apps/frontend/src/locales/de/translation.json
> +      "title": "Datei „{{file}}“ konnte nicht geteilt werden",
Its the only place where we use the ticks around `„{{file}}“`

2025-03-14 10:54 UTC, TomlDev commented on apps/frontend/src/locales/de/translation.json
> +      "filenameAdvice": "Wenn das Austeilen nochmals probiert werden soll, wird die Datei unter dem Namen {{filename}} verteilt",
"erneut versucht" statt nochmals probiert

2025-03-14 10:54 UTC, TomlDev commented on apps/frontend/src/locales/en/translation.json
> +      "CreateCollectFolderForStudentFailed": "Create collect folder for student failed",
Creating the collect folder ...

2025-03-14 10:54 UTC, TomlDev commented on apps/frontend/src/locales/en/translation.json
> +      "errorInfo": "{{failed}} file(s) could not be distributed"
In german its only plural not with `(s)`

2025-03-14 10:54 UTC, TomlDev commented on apps/frontend/src/locales/en/translation.json
> +      "title": "The file \"{{file}}\" could not be shared",
Here you use different ticks then in german

2025-03-14 10:54 UTC, TomlDev commented on apps/frontend/src/locales/en/translation.json
> +      "filenameAdvice": "If you want to try sharing again, the file will be shared under the name {{filename}}",
If you try to share again,

2025-03-14 10:54 UTC, TomlDev commented on apps/frontend/src/locales/en/translation.json
> +      "retryButton": "Try Again"
Retry

2025-03-14 10:54 UTC, TomlDev commented on apps/frontend/src/locales/en/translation.json
> +    "filesSharingStarted": "Files sharing started",
This seems wrong
Sharing files started?

2025-03-14 10:54 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/LessonPage/LessonPage.tsx
> +    const dataForBox = {
toasterData?

2025-03-14 10:54 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/LessonPage/LessonPage.tsx
> +
I think this is a relict of merging and should be removed

2025-03-14 10:54 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/LessonPage/LessonPage.tsx
> +      )}
Could you share a screenshot of this?

2025-03-14 10:54 UTC, TomlDev commented on apps/frontend/src/pages/FileSharing/Table/FileSharingTableColumns.tsx
> +            onFilenameClick(row.original);
Better pass only `row` so you can `row.toggleSelected` when it's a file that is clicked. New task:
https://github.com/edulution-io/edulution-ui/issues/626

2025-03-14 10:54 UTC, TomlDev commented on apps/frontend/src/pages/FileSharing/useFileSharingStore.ts
> +
This was moved to `apps/frontend/src/pages/FileSharing/FilePreview/OnlyOffice/useFileEditorStore.ts`
Please remove it here.

2025-03-14 11:11 UTC, Maddi02 commented on apps/api/src/filesharing/filesharingQueueProcessor.ts
> +      case QUEUE_NAMES.DUPLICATE_FILE_QUEUE:
job name

2025-03-14 11:11 UTC, Maddi02 commented on apps/api/src/filesharing/filesharingQueueProcessor.ts
> +      case QUEUE_NAMES.DUPLICATE_FILE_QUEUE:
I will rename it

2025-03-14 11:15 UTC, Maddi02 commented on apps/api/src/filesharing/filesharing.service.ts
> +  }
Renamed it to `checkIfFolderExists`

2025-03-14 11:24 UTC, Maddi02 commented on apps/frontend/src/components/ui/Table/ScrollableTable.tsx
> +  footer,
`MoveContentDialogBody.tsx`

2025-03-14 11:52 UTC, Maddi02 commented on apps/frontend/src/pages/ClassManagement/LessonPage/LessonPage.tsx
> +      )}
<img width="449" alt="image" src="https://github.com/user-attachments/assets/13e138ea-9044-419f-9557-4ebee182147c" />


<img width="559" alt="image" src="https://github.com/user-attachments/assets/431836bc-0820-4eb6-96a8-81a24d155536" />

2025-03-14 13:14 UTC, TomlDev commented on libs/src/filesharing/types/filesharingProgressDto.ts
> +class FilesharingProgressDto {
As discussed please add the annotations and remove the contructor

2025-03-17 10:46 UTC, TomlDev requested changes
Please have a look 👍🏽

2025-03-17 10:46 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/LessonPage/LessonPage.tsx
> +      )}
I meant the SharingFilesFailedDialogBody

2025-03-17 10:46 UTC, TomlDev commented on libs/src/filesharing/types/filesharingProgressDto.ts
> +export class FilesharingProgressDto {
remove export

2025-03-17 20:27 UTC, Maddi02 commented on apps/api/src/filesharing/filesharing.consumer.ts
> +      currentFile: originFilePath,
Yes. `currentFilePath' is clearer.

2025-03-17 20:51 UTC, Maddi02 commented on apps/frontend/src/pages/ClassManagement/LessonPage/LessonPage.tsx
> +      )}
<img width="504" alt="image" src="https://github.com/user-attachments/assets/58cbffd8-27b3-4064-b008-a93f3116018b" />

2025-03-17 20:57 UTC, Maddi02 commented on apps/frontend/src/components/ui/Table/ScrollableTable.tsx
> +  footer,
```
<ScrollableTable
              ....
              showHeader={false}
              textColorClassname="text-background"
              showSelectedCount={false}
              filterKey="select-filename"
              .....
               />
```

2025-03-18 09:38 UTC, TomlDev approved these changes

2025-03-18 09:38 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/LessonPage/LessonPage.tsx
> +    );
What about something like this, FFTR
```
const hasProgressCompleted = (filesharingProgress?.percent ?? 0) >= 100;
const hasFailedPaths = (filesharingProgress?.failedPaths?.length ?? 0) > 0;

setIsFileSharingProgessInfoDialogOpen(hasProgressCompleted && hasFailedPaths);

2025-03-18 12:52 UTC, merged