Fix creation/display of projects
edulution-io/edulution-ui pull request #238
Opened 2024-10-29 12:38 UTC by TomlDev

2025-01-13 09:14 UTC, michidold requested changes
Some findings, see also in the Edit Project dialog, there are still some issues, like:
- When opening, the name field is not set
- for proxy address there is no validation
- the mail quota expects a number but interprets it as string
- If there is a proxyAddress set, its not safed or just not filled by reopening

2025-01-13 09:14 UTC, michidold commented on libs/src/groups/constants/groupFormSchema.ts
> +    quota: z.string().refine(
There is a false error:
![Bildschirmfoto vom 2025-01-13 09-49-50](https://github.com/user-attachments/assets/f03d7ebe-0d07-46e4-b41a-e68c07871808)

2025-01-13 09:14 UTC, michidold commented on apps/frontend/src/pages/ClassManagement/components/GroupDialog/GroupDialog.tsx
I would rename the button to "Edit Session" if its saved, because you can also remove the session in this dialog:
![grafik](https://github.com/user-attachments/assets/0165bc61-4728-469c-848a-4f09ae0c90fb)

2025-01-14 09:28 UTC, michidold commented
Can you also fix these inconsistancies:
Change to our button component, with small size:
![grafik](https://github.com/user-attachments/assets/45378e7a-2bde-49b2-b7a7-e69e6818fd7c)
Change to small size:
![grafik](https://github.com/user-attachments/assets/33295e7d-3743-413d-8770-035a97b1d736)

2025-01-17 10:21 UTC, TomlDev commented on apps/frontend/src/locales/de/translation.json
> +    "proxyAddresses": "Proxy Adressen",
Renamed to Proxy Email-Adressen

2025-01-17 10:21 UTC, TomlDev commented on apps/frontend/src/locales/en/translation.json
> +    "proxyAddresses": "Proxy Adressen",
Changed to Proxy Email-Adresses

2025-01-17 11:52 UTC, TomlDev commented
> Some findings, see also in the Edit Project dialog, there are still some issues, like:
> 
>     * When opening the name field is not set
There seems to be a new bug introduced by changes in the LMN API, I reported it.
>     * for proxy address there is no validation
Added 👍🏽 
>     * the mail quota expects a number but interprets it as string
Fixed 👍🏽 
>     * If there is a proxyAddress set, its not safed or just not filled at render
There seems to be a new bug introduced by changes in the LMN API, I reported it.

Now there is a placeholder to show an example fill out:
![grafik](https://github.com/user-attachments/assets/9a223ec4-2b7f-4dcd-95e4-13fe159b14db)

2025-01-17 11:55 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/LessonPage/UserArea/UserArea.tsx
> +    30;
I think it's not worth the effort, we must rework the design.

2025-01-17 12:01 UTC, TomlDev commented on apps/frontend/src/locales/de/translation.json
> +    "proxyAddresses": "Proxy Adressen",
Added a placeholder example
![grafik](https://github.com/user-attachments/assets/e576a656-92f6-45cb-8ee2-7cf17cc26950)
And for proxy addresses this
![grafik](https://github.com/user-attachments/assets/430b3448-a2b3-45cb-98d2-285588cd58f4)

For quota its too complex, this is the description from LMN:

> Attributes for quota
> 
>     mailquota is an attribute to add quota for email, as integer (e.g. "mailquota": 100)
>     quota is an attribute to add quota per share, as an object. Examples:
> 
> "quota": [{"quota":50,"share":"default-school"]
> 
> or
> 
> "quota": [{"quota":500,"share":"agy"}, {"quota":300,"share":"linuxmuster-global"}]


I have created a new task for this https://github.com/edulution-io/edulution-ui/issues/370

2025-01-23 09:20 UTC, michidold commented on apps/frontend/src/pages/ClassManagement/LessonPage/UserArea/UserArea.tsx
> +    30;
Ok, can you add a concrete task to do so?

2025-01-23 09:25 UTC, michidold commented on apps/frontend/src/locales/en/translation.json
> +    "proxyAddresses": "Proxy Adressen",
Still german text here.

2025-01-23 09:41 UTC, michidold requested changes
Found some stuff, please have a look

2025-01-23 09:41 UTC, michidold commented on apps/frontend/src/pages/ClassManagement/components/GroupDialog/GroupDialog.tsx
I had to issues with this dialog. First you cant close it
[Bildschirmaufzeichnung vom 2025-01-23 10-31-05.webm](https://github.com/user-attachments/assets/2bdf499c-f61d-4e00-8ec3-52408c9241c7)
Second, on delete there is no redirect.
[Bildschirmaufzeichnung vom 2025-01-23 10-33-10.webm](https://github.com/user-attachments/assets/24b023fc-9ef5-4d63-b84f-84418b5be60f)

2025-01-23 10:04 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/LessonPage/UserArea/UserArea.tsx
> +    30;
I think we already had one in Jira...
New one here: https://github.com/edulution-io/edulution-ui/issues/385

2025-02-05 12:50 UTC, michidold approved these changes
Looks good

2025-02-05 12:50 UTC, merged