Poll isRunning from conferences minutely and notify users
edulution-io/edulution-ui pull request #239
Opened 2024-10-30 10:03 UTC by TomlDev

See issue

[Update .env](https://doku.netzint.de/doku.php?id=intern:technik:schulserver:edulution:guides:dev-env)

2024-11-18 14:03 UTC, michidold requested changes
One small question.

2024-11-18 14:03 UTC, michidold commented on apps/api/src/conferences/conferences.service.ts
> +  }
Is there a reason why this is not handled by the `@Interval` decorator as in scheduled groups fetch?

2024-11-19 10:18 UTC, michidold requested changes
I still have a issue were the running state is not updated or throws false errors:
[Bildschirmaufzeichnung vom 2024-11-19 11-15-56.webm](https://github.com/user-attachments/assets/bae0f93b-025f-48ba-baf9-ee93846c6204)

2024-11-29 13:35 UTC, michidold requested changes
Have a issue when starting the conference. See comment.

2024-12-03 09:09 UTC, michidold approved these changes
Looks good. Maybe we can optimize that in another task by opening the frame while its loading

2024-12-03 09:09 UTC, michidold commented on apps/api/src/conferences/conferences.service.ts
Maybe we can optimize that in another task by opening the frame while its loading

2024-12-03 09:11 UTC, merged

2024-12-03 09:12 UTC, TomlDev commented
Created a task:
https://github.com/edulution-io/edulution-ui/issues/288