Replace ControlPanel with a Window frame
edulution-io/edulution-ui pull request #265
Opened 2024-11-14 12:27 UTC by TomlDev

See the issue for the previous implementation. It just didn't look very professional/state of the art.

Change to a normal window bar that allows maximizing, minimizing and windowed mode (and closing).

https://github.com/user-attachments/assets/b1b6a1ce-48b1-4ea7-9c69-0e2dc8e71280

Currently conferencing and desktop-deployment are supported (vdi could not be tested because it is not running locally).
And in the file manager the fullscreen preview was also switched:
![grafik](https://github.com/user-attachments/assets/081874ea-bfef-41c6-b77d-33bcdc7c96e9)

### Key changes
- Remove the unused ControlPanel component
- Introduce a new ResizableWindow component
- Add a hook to listen for window size changes
- Rework the frame store to separate embedded frames, that have no windowed mode capability
- Refactor some file manager related files

### Mobile view

https://github.com/user-attachments/assets/a83b8bdc-6875-47e2-844c-59057270b1bc

Todo: https://github.com/edulution-io/edulution-ui/issues/319

2024-12-20 15:51 UTC, michidold requested changes
Found some stuff, please have a look.

2024-12-20 15:51 UTC, michidold commented on apps/frontend/src/components/framing/ResizableWindow/CloseButton.tsx
> +    <div className="text-2xl">×</div>
Have you tested `<MdClose />` from react-icons? Maybe it fits better. Anyways it looks awesome .
##FFTR

2024-12-20 15:51 UTC, michidold commented on apps/frontend/src/pages/DesktopDeployment/DesktopDeploymentPage.tsx
> +      <NativeAppHeader
A scrollbar appears at least on chrome:
![grafik](https://github.com/user-attachments/assets/a8ca1d81-b2e0-4e06-b3ec-24851163cc31)

2024-12-20 15:51 UTC, michidold commented on apps/frontend/src/pages/FileSharing/previews/FileViewer.tsx
> +          disableMinimizeWindow
Can we make this minimizeable as well?

2024-12-20 15:51 UTC, michidold commented on libs/src/filesharing/constants/routes.ts
> +const ONLY_OFFICE_ROUTE = '/onlyOffice';
I would use lower case and the slash isn't needed i think. But have a look.
##FFTR

2024-12-20 15:51 UTC, michidold commented on apps/frontend/src/components/framing/ResizableWindow/ResizableWindow.tsx
> +    const width = isMobileView ? window.innerWidth : window.innerWidth - SIDEBAR_WIDTH;
On smartphone at least VDI is not useable. Think we should block it on mobile phone, but not for tablets

2024-12-20 15:51 UTC, michidold commented on apps/frontend/src/components/framing/ResizableWindow/ResizableWindow.tsx
> +          />
On mobile these buttons are not clickable if its minimized.
[Bildschirmaufzeichnung vom 2024-12-20 16-50-53.webm](https://github.com/user-attachments/assets/9fb0bf4d-99e1-47ae-ae0b-c1b35674771b)

2025-01-07 10:19 UTC, TomlDev commented on apps/frontend/src/pages/FileSharing/previews/FileViewer.tsx
> +          disableMinimizeWindow
The behavior is taken from the previous implementation, I think if we wanted to make it minimizable we have to take more edge cases into consideration. Therefore I would not want to add this change in this PR.

2025-01-07 10:21 UTC, TomlDev commented on libs/src/filesharing/constants/routes.ts
> +const ONLY_OFFICE_ROUTE = '/onlyOffice';
I replaced the original occurrences 
![grafik](https://github.com/user-attachments/assets/b1ba5740-b78c-4b8b-8c85-729512507e6f)
![grafik](https://github.com/user-attachments/assets/d505fb35-e3ca-4cd6-9c66-7253e7041b96)

I would not want to introduce any changes in this PR for the lower case. You want me to move the slash outside of the const?

2025-01-07 10:58 UTC, TomlDev commented on apps/frontend/src/components/framing/ResizableWindow/ResizableWindow.tsx
> +          />
I think it's a problem of touch emulation:

https://github.com/user-attachments/assets/0430fd69-d660-4a8f-a21f-142d69ad750a

In firefox with touch enabled I had to click twice. Will test it on mobile.

2025-01-07 14:08 UTC, TomlDev commented on libs/src/filesharing/constants/routes.ts
> +const ONLY_OFFICE_ROUTE = '/onlyOffice';
The navigation still works, I could not find other places where it was used so I hope the change has no other impacts 👍🏽

2025-01-07 14:10 UTC, TomlDev commented on apps/frontend/src/components/framing/ResizableWindow/ResizableWindow.tsx
> +    const width = isMobileView ? window.innerWidth : window.innerWidth - SIDEBAR_WIDTH;
With the rework at least the displaying/controls should work. If it makes sense is another question :D

2025-01-07 14:10 UTC, TomlDev commented on apps/frontend/src/components/framing/ResizableWindow/ResizableWindow.tsx
> +          />
There was actually a problem with it but it's fixed now. Should work on mobile now correctly.

2025-01-08 08:20 UTC, michidold approved these changes
Looks good

2025-01-08 08:27 UTC, merged