Improve conferencing UX
edulution-io/edulution-ui pull request #267
Opened 2024-11-14 13:23 UTC by TomlDev

see issue description for task list

2024-11-20 11:02 UTC, michidold requested changes
Found some stuff, please have a look

2024-11-20 11:02 UTC, michidold commented on apps/frontend/src/pages/ConferencePage/Table/ConferencesTableColumns.tsx
If a user leaves the conference by clicking inside on "Konferenz verlassen", the state joined is not updated.
![grafik](https://github.com/user-attachments/assets/89099e88-678b-431a-8b59-0590bf3fbbb7)

So if he rejoins the counter increments.
![Bildschirmfoto vom 2024-11-20 11-54-34](https://github.com/user-attachments/assets/dc11ee13-93f8-47f1-a8e9-bbba9978666c)
Also there is a issue with the joinedAttendees object, which has "VIEWER" under "lastName"

2024-11-20 11:02 UTC, michidold commented on apps/frontend/src/pages/ConferencePage/Table/ConferencesTableColumns.tsx
Maybe the sorting of "Password" and "Invited" columns doesn't make sense and could be removed.

2024-11-26 13:40 UTC, TomlDev commented on apps/frontend/src/pages/ConferencePage/CreateConference/CreateConferenceDialogBody.tsx
Should be fixed by turning autoComplete off 👍🏽

2024-11-26 13:57 UTC, TomlDev commented on apps/frontend/src/pages/ConferencePage/Table/ConferencesFloatingButtons.tsx
> +      }, selectedConferenceIds.length > 0),
I changed it to the same scroll area like in filesharing, if you want it to be changed in general I would suggest a new task for this 👍🏽

2024-11-26 13:57 UTC, TomlDev commented on apps/frontend/src/pages/ConferencePage/CreateConference/CreateConferenceDialogBody.tsx
Should be fixed. I added it to the FormField since it's only used in places where we probably don't want the autocompletion

2024-11-26 14:12 UTC, TomlDev commented on apps/frontend/src/pages/ConferencePage/Table/ConferencesTableColumns.tsx
Fixed the object 👍🏽 
The missing state update is because BBB still returns 2 attendees:
```

    <participantCount>2</participantCount>
...
    <moderatorCount>2</moderatorCount>
    <attendees>
        <attendee>
            <userID>global-admin</userID>
            <fullName>Global Admin</fullName>
            <role>MODERATOR</role>
            <isPresenter>false</isPresenter>
            <isListeningOnly>false</isListeningOnly>
            <hasJoinedVoice>false</hasJoinedVoice>
            <hasVideo>false</hasVideo>
            <clientType>HTML5</clientType>
        </attendee>
        <attendee>
            <userID>global-admin</userID>
            <fullName>Global Admin</fullName>
            <role>MODERATOR</role>
            <isPresenter>true</isPresenter>
            <isListeningOnly>false</isListeningOnly>
            <hasJoinedVoice>false</hasJoinedVoice>
            <hasVideo>false</hasVideo>
            <clientType>HTML5</clientType>
        </attendee>
    </attendees>
    ```
    
    I don't think it's worth to invest much time in trying to fix/hack that

2024-11-26 14:15 UTC, TomlDev commented on apps/frontend/src/pages/ConferencePage/Table/ConferencesTableColumns.tsx
I think it makes sense. But there was a bug for sorting passwords. Now it sorts if the conferences have a password or not.
For the invited it also makes sense to sort it by the count of invited users

2024-11-29 14:31 UTC, michidold requested changes
Two small findings left

2024-11-29 14:31 UTC, michidold commented on apps/frontend/src/components/shared/FormField.tsx
> +              autoComplete="off"
`autoComplete="off"` doesn't work on newer chrome versions. With `autoComplete="new-password"` it works for me.

2024-11-29 14:31 UTC, michidold commented on apps/frontend/src/pages/ConferencePage/ConfereneceDetailsDialog/ConferenceDetailsDialog.tsx
> +    if (isLoading || !selectedConference) return <CircleLoader className="mx-auto mt-5" />;
Needs to be changed in CreateConferencesDialog.tsx and DeleteConferencesDialog.tsx as well

2024-12-02 10:09 UTC, TomlDev commented on apps/frontend/src/pages/FileSharing/FileSharingPage.tsx
> -      {isLoading && <LoadingIndicator isOpen={isLoading} />}
Removed because it's there already some lines below. FFTR

2024-12-09 09:51 UTC, michidold approved these changes
Looks good

2024-12-09 09:58 UTC, merged