Conferences: public access
edulution-io/edulution-ui pull request #273
Opened 2024-11-21 14:26 UTC by TomlDev

### Changed

- Added isPublic property to conferences
- Added password check for registered users joining a conference
- Added endpoints to
  - get a public, sanitized conference
  - join a public conference
  - subscribe to SSE events for public users
    -> Instead of subscribing by name the public users subscribe generally to stop/start events of the conference by the meeting ID
- Filter passwords from conferences when you are not the creator
- Extend the FormField/RadioGroupFormField
- Move `findAppConfigByName` to shared-lib
- Remove the unnecessary `translateKey` function (replaced with our local i18n instance)
- Extend CircleLoader, QRCodeDisplay
- Extract QRCodeWithCopyButton
- Added translations
- Display the QR code + isPublic selector in conference dialog
- Add page to join public conferences

2024-12-03 08:18 UTC, michidold requested changes
Had some findings. Please have a look

2024-12-03 08:18 UTC, michidold commented on apps/frontend/src/pages/Surveys/Editor/dialog/SharePublicSurveyDialog.tsx
Think its not related with this file, but the survey editor is corrupted in some case. In dev it works just fine. Have you any idea why thats happend?

2024-12-17 09:42 UTC, TomlDev commented on apps/frontend/src/pages/ConferencePage/PublicConference/PublicConferencePage.tsx
> +  }, [publicConference, isConferenceAppActivated]);
It should also rerender if the password is removed, if the isPublic state changes, and the isRunning state.
I would leave it with 
```
  }, [publicConference]);

2024-12-17 09:48 UTC, TomlDev commented on apps/api/src/conferences/conferences.controller.ts
> +  join(@Param('meetingID') meetingID: string, @Query('password') password: string, @GetCurrentUser() user: JWTUser) {
The password is used when a registered user logs in and he is not invited
```
GET http://localhost:5173/edu-api/conferences/join/5e9676a3-60d7-4dd5-9f38-243d87ed8496?password=123

2024-12-17 09:49 UTC, TomlDev commented on apps/api/src/conferences/conferences.service.ts
> +      const isCorrectPassword = conference.password ? conference.password === password : true;
No, only invited users can join without password auth.

2024-12-17 09:59 UTC, TomlDev commented on apps/api/src/conferences/conferences.service.ts
> +    ])[0];
I still use the field to know if the conference is password protected. I renamed the function to `replaceForeignConferencesPasswords`

2024-12-17 10:01 UTC, TomlDev commented on apps/frontend/src/locales/de/translation.json
> +    "isNotPublicOrDoesNotExist": "Die Konferenz konnte nicht gefunden werden. Entweder sie ist nicht öffentlich, oder sie existiert nicht.",
Yes when a user sets it private again. Changed anyway.

2024-12-17 10:06 UTC, TomlDev commented on apps/frontend/src/pages/ConferencePage/PublicConference/PublicConferencePage.tsx
> +  const automaticallyJoinAsRegisteredUser = async () => {
https://github.com/edulution-io/edulution-ui/issues/327

2024-12-17 10:17 UTC, TomlDev commented on apps/frontend/src/pages/LoginPage/LoginPage.tsx
> +      console.error(e);
It's not pointless because there are 10 lines of code in the try catch block and on a lot of places an error could occur.
But from my experience I can say that a try/catch that does nothing is pointless... Or even worse it can cost you minutes to hours to debug....

2024-12-17 10:21 UTC, TomlDev commented on apps/frontend/src/router/routes/PublicRoutes.tsx
> +const getPublicRoutes = () => [
DM already takes care:
https://github.com/edulution-io/edulution-ui/pull/170/files#diff-3e89c30872b1fccb2b567a83fa2de794726a458958b1e73a4b33440779fdee5dR16

2024-12-18 07:34 UTC, michidold commented on apps/frontend/src/pages/ConferencePage/PublicConference/PublicConferencePage.tsx
> +  }, [publicConference, isConferenceAppActivated]);
But there is always a new event stream created and on the sse side the update for the starting event goes to the old one:
[Bildschirmaufzeichnung vom 2024-12-18 08-31-58.webm](https://github.com/user-attachments/assets/28db3584-3009-4044-a448-cfb6c9e3d447)

2024-12-18 08:07 UTC, michidold commented on apps/frontend/src/pages/LoginPage/LoginPage.tsx
> +      console.error(e);
Think we could safely remove the try catch block, its a relic when we used the finally block to trigger the following queries. The error from auth itself is set in the useEffect on line 49.

2024-12-18 08:13 UTC, michidold requested changes
The auto join does not work

2024-12-18 08:51 UTC, TomlDev commented on apps/frontend/src/pages/LoginPage/LoginPage.tsx
> +      console.error(e);
Removed 👍🏽

2024-12-18 10:07 UTC, TomlDev commented on apps/frontend/src/pages/ConferencePage/PublicConference/PublicConferencePage.tsx
> +  }, [publicConference, isConferenceAppActivated]);
Okay, changed it to `[publicConference?.meetingID]);` 👍🏽 
Now it should work.

2024-12-18 12:28 UTC, michidold approved these changes
Looks good, only two small things

2024-12-18 12:28 UTC, michidold commented on apps/frontend/src/pages/ConferencePage/Table/ConferencesFloatingButtons.tsx
> +import i18next from 'i18next';
Is there a reason to not use the `useTranslation` hook?

2024-12-18 12:28 UTC, michidold commented on apps/frontend/src/pages/ConferencePage/Table/ConferencesTableColumns.tsx
> +              toast.info(i18next.t(`conferences.${isRunning ? 'stopped' : 'started'}`));
Normally we import i18n from `@/i18n`

2024-12-18 12:36 UTC, merged