Remove deprecated OnlyOffice configuration
edulution-io/edulution-ui pull request #281
Opened 2024-11-27 20:44 UTC by Maddi02

Replaced the old OnlyOffice configuration with a new structured approach using ExtendedOptionKeys and ExtendedOptionField. Updated associated files and components to align with the new config structure for better maintainability and clarity.

2024-11-28 10:05 UTC, TomlDev commented on apps/frontend/src/pages/Settings/AppConfig/AppConfigPage.tsx
> +    const newExtendedOptions = Array.isArray(currentConfig.extendedOptions)
Why can `currentConfig.extendedOptions` be something different than an array or undefined?

2024-11-28 10:05 UTC, TomlDev commented on apps/frontend/src/pages/Settings/AppConfig/AppConfigPage.tsx
> +      : [];
Why is this whole `newExtendedOptions` necessary?

2024-11-28 10:47 UTC, TomlDev commented on apps/frontend/src/pages/Settings/AppConfig/AppConfigPage.tsx
> +    const extendedOptions = form.getValues(`${settingLocation}.extendedOptions`) as AppConfigOptions[];
Type casting is wrong, should be `AppConfigExtendedOption`

2024-11-28 10:52 UTC, TomlDev commented on apps/frontend/src/pages/FileSharing/hooks/useOnlyOffice.ts
> +  const documentServerURL = getExtendedOptionValue(appConfigs, ExtendedOptionKeys.ONLY_OFFICE_URL);
![grafik](https://github.com/user-attachments/assets/ec24b453-3efb-4b5d-988f-7bfa49351e50)

2024-11-28 11:05 UTC, TomlDev commented on apps/frontend/src/pages/Settings/AppConfig/components/ExtendedOptionsForm.tsx
> +    <form
![grafik](https://github.com/user-attachments/assets/44a91534-3b6c-4156-a88c-ec4d1a3d586d)

2024-12-09 11:48 UTC, michidold requested changes
Looks good over all. Some minor suggestions

2024-12-09 11:48 UTC, michidold commented on apps/frontend/src/pages/Settings/AppConfig/AppConfigPage.tsx
> +    const extendedOptions = form.getValues(`${settingLocation}.extendedOptions`) as ExtendedOptionKeysDto;
I think setting it to a empty object is safer than typecasting:
`const extendedOptions = form.getValues(`${settingLocation}.extendedOptions`) || {};`

2024-12-09 11:48 UTC, michidold commented on apps/frontend/src/pages/Settings/AppConfig/appConfigOptions.ts
> +      ],
Is this intended to be the place, to define all extendedOptions? I would define these in another file. Its a constant and could be placed in libs

2024-12-09 11:48 UTC, michidold commented on apps/frontend/src/pages/Settings/AppConfig/appConfigSchema.ts
We should consider adding some type of validation. Can you add a issue?

2024-12-09 11:48 UTC, michidold commented on apps/frontend/src/pages/Settings/AppConfig/components/AppConfigFormField.tsx
We have still a custom FormField component, can't we use that in here? At least we must use the `autoComplete='new-password` option on the input field to prohibit the browser of inserting the safed creds of the user

2024-12-09 11:48 UTC, michidold commented on libs/src/appconfig/constants/extendedOptionKeys.ts
> +export default ExtendedOptionKeys;
I would prefere a const object:
```typescript
const ExtendedOptionKeys = {
  ONLY_OFFICE_URL: 'ONLY_OFFICE_URL',
  ONLY_OFFICE_JWT_SECRET: 'ONLY_OFFICE_JWT_SECRET',
} as const;

export default ExtendedOptionKeys;

```

2024-12-09 12:01 UTC, TomlDev commented on apps/frontend/src/pages/Settings/AppConfig/appConfigSchema.ts
Yes https://github.com/edulution-io/edulution-ui/issues/302

2024-12-09 12:03 UTC, TomlDev commented on apps/frontend/src/pages/Settings/AppConfig/components/AppConfigFormField.tsx
Yes we have that component but it's cause many issues if you try to use it.
I already spent some hours trying different things but it's a little messed up, so we decided to create a new one that will work.

2024-12-09 13:48 UTC, michidold approved these changes
Looks good

2024-12-09 13:56 UTC, merged