270 Add Base for the databse migrations
edulution-io/edulution-ui pull request #297
Opened 2024-12-03 16:02 UTC by maierdominik

New start without using an external plugin

270: 
* adapt schema sucht that each document has the property `schemaVersion`
* create migration where the value for `schemaVersion` is set to `0` to test it

2024-12-04 08:18 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/components/GroupDialog/GroupPropertiesTable.tsx
> +          return watch(groupProperty.name) as string;
Instead change line 14 to 
`name: keyof Omit<GroupForm, 'admins' | 'admingroups' | 'members' | 'membergroups'>`

2024-12-05 07:58 UTC, TomlDev commented on apps/api/src/appconfig/appconfig.migration.service.ts
> +    Logger.log('⬆ ... executing Migrations', AppConfigMigrationService.name);
I would combine the two logging lines
```
    Logger.log(`⬆ ️⬆️ Executing migratings`, AppConfigMigrationService.name);

2024-12-05 08:05 UTC, TomlDev commented on apps/api/src/appconfig/appconfig.migration.service.ts
> +            migrationNumber: newMigrationNumber,
I dislike the name `migrationNumber`, what about `schemaVersion`, this is also used in the MongoDB docs

2024-12-05 08:06 UTC, TomlDev commented on apps/api/src/appconfig/appconfig.migration.service.ts
> +      Logger.error(`⬆     Error while running Migration "${migrationName}": ${e}`, AppConfigMigrationService.name);
Is there a reason for the whitespaces?

2024-12-05 08:08 UTC, TomlDev requested changes
Looks good 👍🏽

2024-12-05 12:25 UTC, maierdominik commented on apps/api/src/appconfig/appconfig.migration.service.ts
> +      Logger.error(`⬆     Error while running Migration "${migrationName}": ${e}`, AppConfigMigrationService.name);
Reverted.
My thought were that it is easier to differ this line of output from all the other lines.

2024-12-06 10:19 UTC, TomlDev approved these changes
👍🏽

2024-12-06 10:23 UTC, merged