292 Adapt language for survey-js
edulution-io/edulution-ui pull request #299
Opened 2024-12-04 14:57 UTC by maierdominik

292 fix language for surveys
    * pass the language provided in the user store to the components (tried to use i18next.language)

2024-12-05 08:26 UTC, TomlDev commented on apps/frontend/src/pages/Surveys/Tables/dialogs/ResultVisualizationDialogBody.tsx
> +      language={user?.language}
Since you only call the store to pass the prop down it would make a lot more sense to call the store inside `ResultVisualization`

2024-12-05 08:26 UTC, TomlDev commented on apps/frontend/src/pages/Surveys/Tables/dialogs/ResultTableDialogBody.tsx
> +        language={user?.language}
Since you only call the store to pass the prop down it would make a lot more sense to call the store inside `ResultTable`

2024-12-05 08:27 UTC, TomlDev commented on apps/frontend/src/pages/Surveys/Tables/dialogs/ParticipateDialog.tsx
> +          language={user?.language}
Since you only call the store to pass the prop down it would make a lot more sense to call the store inside `ParticipateDialogBody`

2024-12-05 08:27 UTC, TomlDev commented on apps/frontend/src/pages/Surveys/Public/ParticipatePublicSurvey.tsx
> +          language={user?.language}
Since you only call the store to pass the prop down it would make a lot more sense to call the store inside `ParticipateDialogBody`

2024-12-05 08:28 UTC, TomlDev commented on apps/frontend/src/pages/Surveys/Editor/SurveyEditorForm.tsx
> +        language={user.language}
Offtopic: Could you please extract the `formSchema` to it's own file in shared-lib please

2024-12-05 08:35 UTC, TomlDev commented on apps/frontend/src/pages/Surveys/Editor/components/SurveyEditor.tsx
> +  language?: string;
Offtopic: Please use `form: UseFormReturn<SurveyDto>;` in line 22 to remove the `any`. The same in the `<SaveSurveyDialog />` component.
You will get some type errors but they are correct. In `convertJSONToSurveyFormula` you probably don't want to return `undefined`, instead you could return a default formula:
```

const convertJSONToSurveyFormula = (formula: JSON): SurveyFormula => {
  try {
    const typedFormula = formula as unknown as SurveyFormula;
    const isValidFormula = isSurveyFormula(typedFormula);
    if (isValidFormula) {
      return typedFormula;
    }
  } catch (error) {
    toast.error(t(SurveyErrorMessages.SurveyFormulaStructuralError));
  }

  return {title: ''};
};
```

You can replace the `any` because the form is typed:
```

  const form = useForm<SurveyDto>({        // <----- here
    mode: 'onChange',
    resolver: zodResolver(formSchema),
    defaultValues: initialFormValues,
  });

2024-12-05 08:36 UTC, TomlDev submitted a review, later dismissed
Some small refactorings 👍🏽

2024-12-09 14:52 UTC, michidold requested changes
Some findings, please have a look

2024-12-09 14:52 UTC, michidold commented on apps/frontend/src/pages/Surveys/Editor/components/SurveyEditor.tsx
> +  localization.currentLocale = user?.language ?? 'de';
That doesn't work and leads to a crash. If user.language is set to system. Also the language stored is 'de-DE', which is incompatible with this setting. 

Replace it by:
```typescript
  const userLanguage = (user?.language !== 'system' ? user?.language : navigator?.language) || 'de-DE';
  const locale = userLanguage.split('-')[0];
  editorLocalization.defaultLocale = locale;
  localization.currentLocale = locale;
  ```

2024-12-09 14:52 UTC, michidold commented on apps/frontend/src/pages/Surveys/Tables/components/ResultTable.tsx
> +    surveyVisuTable.locale = user?.language ?? 'de';
Same as for the editor. Think you should rework the useLanguage store with the functions described above and use the `lang` from there. useLanguage should only be a hook, since it doesn't need to store things.

2024-12-09 14:52 UTC, michidold commented on apps/frontend/src/pages/Surveys/Tables/components/ResultVisualization.tsx
> +    visualizationPanel.locale = user?.language ?? 'de';
same here

##FFTR

2024-12-09 14:52 UTC, michidold commented on apps/frontend/src/pages/Surveys/Tables/dialogs/ParticipateDialogBody.tsx
> +  surveyModel.locale = user?.language ?? 'de';
same here

##FFTR

2024-12-10 17:00 UTC, maierdominik commented on apps/frontend/src/pages/Surveys/Editor/components/SurveyEditor.tsx
> +  localization.currentLocale = user?.language ?? 'de';
I guess that is only relevant for the `navigator.language`, since:
![image](https://github.com/user-attachments/assets/df3135c1-ace5-4e10-b612-6fc6824b0101)

2024-12-11 11:17 UTC, michidold requested changes
Two comments left

2024-12-12 13:42 UTC, michidold approved these changes
Looks good

2024-12-12 13:52 UTC, merged