286 Add veyon webapi to classmgmt
edulution-io/edulution-ui pull request #305
Opened 2024-12-10 10:58 UTC by michidold

2025-01-16 10:03 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/LessonPage/UserArea/FrameBufferImage.tsx
The refresh button is missing. If you are within the LessonsPage, the user IP addresses are no longer updated, i.e. if a user logs in first, the teacher does not notice this and has to close the session again and reopen it

2025-01-16 15:21 UTC, TomlDev requested changes
Looks very good 👍🏽

2025-01-16 15:21 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/LessonPage/UserArea/UserCard.tsx
> +          </div>
Why is the symbol better than the name letters?
![grafik](https://github.com/user-attachments/assets/f5900589-4bb8-4d7e-a2df-7aeb5b32b4e4)

I think as soon as a user logged in to one PC it will never go back to the letters, so maybe we can remove that. Since the IP does not seem to be cleared.

2025-01-16 15:21 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/useVeyonApiStore.ts
> +        `veyon/${ip}`,
In other PRs we moved the path `veyon` to a const file, what do you think about doing that here too?

2025-01-16 15:21 UTC, TomlDev commented on apps/frontend/src/pages/ClassManagement/useVeyonApiStore.ts
> +  authenticateVeyonClients: async (ip: string, veyonUser: string) => {
is plural correct? ClientS

2025-01-16 15:21 UTC, TomlDev commented on apps/frontend/src/pages/Settings/AppConfig/classmgmt/AddVeyonProxyDialog.tsx
Is there a special reason to name the folder `classMgmt`?

2025-01-28 15:02 UTC, TomlDev approved these changes
You can merge after you fixed the review findings

2025-01-28 15:17 UTC, merged

2025-01-29 14:34 UTC, michidold commented on apps/api/src/veyon/veyon.service.ts
> +        `/authentication/${ip}`,
Its done in veyon itself, its connected to ldap and therefore you only have access if permitted.

2025-01-29 14:37 UTC, michidold commented on apps/api/src/veyon/veyon.controller.ts
> +  ): Promise<void> {
At the moment there are only two hard coded configs.