246 Classes Section Overflows Instead of Becoming Scrollable - Dashboard
edulution-io/edulution-ui pull request #314
Opened 2024-12-12 13:36 UTC by maierdominik

Issue: https://github.com/edulution-io/edulution-ui/issues/246

246:
* adjust gaps and margins to unify the styling of the dashboard cards
* assign an id to the `Groups` card such that the height is known
* calculate the space that is available for the content of the card and use it

2024-12-13 07:38 UTC, michidold requested changes
Seems the cards are not equally high

2024-12-13 07:38 UTC, michidold commented on apps/frontend/src/components/shared/Card/card.module.scss
> +    margin: -3px;
The border should be 4px like on the other cards. And I would keep the variable $border

2024-12-13 07:38 UTC, michidold commented on apps/frontend/src/pages/Dashboard/MobileFileAccess/MobileFileAccessCard.tsx
This could be a bit shorter:
![grafik](https://github.com/user-attachments/assets/002303dc-f1f7-4c86-a9d3-ae64b2669611)

2024-12-13 07:38 UTC, michidold commented on apps/frontend/src/pages/Dashboard/Home.tsx
> +      <div className="flex flex-col gap-8">
These two could be combined

2024-12-13 11:45 UTC, maierdominik commented on apps/frontend/src/components/shared/Card/card.module.scss
> +    margin: -3px;
Reverted,
but in my experience, the border of the other elements seem more narrow than this one with the gradient effect, after the render.

2024-12-13 11:46 UTC, maierdominik commented on apps/frontend/src/pages/Dashboard/MobileFileAccess/MobileFileAccessCard.tsx
I am not exactly sure how you mean it or what elements you mean,
in hope of meating your expecations i set the minimum height too `200` (previously 280)

![image](https://github.com/user-attachments/assets/e77f2ed3-777f-4d44-9b7b-844b67fc3cc1)

2024-12-18 08:15 UTC, michidold commented on apps/frontend/src/pages/Dashboard/MobileFileAccess/MobileFileAccessCard.tsx
Sorry, thought its obviouse -> The mobil access card and the classes card are not the same size

2024-12-18 08:54 UTC, michidold requested changes
Had a error during render. Have a look

2024-12-18 08:54 UTC, michidold commented on apps/frontend/src/pages/Dashboard/DashboardPage.tsx
> +        <div className={`flex flex-col-reverse gap-8 md:flex-row md:max-h-[${pageBarsHeight}px]`}>
These two divs could be combined.

2024-12-18 08:54 UTC, michidold commented on apps/frontend/src/pages/Dashboard/DashboardPage.tsx
> +  const pageBarsHeight = useElementHeight([BLANK_LAYOUT_HEADER_ID, DASHBOARD_DESCRIPTION_ID, FOOTER_ID]);
There is a error thrown by this hook:
[Bildschirmaufzeichnung vom 2024-12-18 09-34-40.webm](https://github.com/user-attachments/assets/8c1ca56d-e168-4aa2-81aa-58f3209ba227)

2024-12-18 08:54 UTC, michidold commented on apps/frontend/src/pages/Dashboard/Groups.tsx
> +            <BadgeField
Think the error mentioned above occurs, because the badge field is rendered first and then the height is updated, which causes a render loop.

2024-12-19 14:55 UTC, maierdominik commented on apps/frontend/src/pages/Dashboard/Groups.tsx
> +            <BadgeField
The concerning element is not  the BadgeField but the dashboard description 
 `DASHBOARD_DESCRIPTION_ID`

2024-12-19 14:56 UTC, maierdominik commented on apps/frontend/src/pages/Dashboard/DashboardPage.tsx
> +  const pageBarsHeight = useElementHeight([BLANK_LAYOUT_HEADER_ID, DASHBOARD_DESCRIPTION_ID, FOOTER_ID]);
I removed the hook
If the size should adjust itself, I would create a new Issue for this task

2024-12-20 14:41 UTC, michidold requested changes
Found some stuff, please have a look

2024-12-20 14:41 UTC, michidold commented on apps/frontend/src/components/shared/Card/Card.tsx
> +        className={cn('h-full w-full p-[20px]', className)}
Think this has no effect?

2024-12-20 14:41 UTC, michidold commented on apps/frontend/src/pages/Dashboard/DashboardPage.tsx
> +  const column1 = (
This card is still too big

2024-12-20 14:41 UTC, michidold commented on apps/frontend/src/pages/Dashboard/DashboardPage.tsx
> +          <Groups />
On mobile view there is nothing shown:
![grafik](https://github.com/user-attachments/assets/843e4730-4565-4f04-b084-0259fb55aed9)

2025-01-09 12:33 UTC, merged