Niedu UI 348 move imap data from env to db
edulution-io/edulution-ui pull request #334
Opened 2024-12-19 18:17 UTC by maierdominik

NIEDUUI 348 move imap data from env to db

2024-12-19 18:22 UTC, maierdominik commented on apps/api/src/mails/mails.service.ts
> +    const imapOptions = getExtendedOptionValue(
As i understand the function it should return a single value for a extended options field. But it does not.

Does this really work for the other occurances.

2024-12-20 14:05 UTC, michidold requested changes
Found some stuff, please have a look

2024-12-20 14:05 UTC, michidold commented on libs/src/appconfig/constants/extendedOptions/imapMailFeed.ts
> +];
Here the title and descriptions are wrong. ExtendedOptionField needs to be type input. Please add a task where we add:
- input type number
- boolean Switch
as options

2024-12-20 14:05 UTC, michidold commented on libs/src/dashboard/constants/pull-time-interval.ts
> +export const FEED_PULL_TIME_INTERVAL_SLOW = 5000;
I would keep 60s

2025-01-07 14:03 UTC, maierdominik commented
Another Certification Error:

![image](https://github.com/user-attachments/assets/5a3de000-ba17-4809-9ed3-8f465c727eaa)

2025-01-08 08:49 UTC, michidold commented on libs/src/appconfig/constants/extendedOptions/imapMailFeed.ts
> +];
Its still password type

2025-01-08 09:29 UTC, michidold requested changes
Some findings left, please test your implementation before requesting a review.

2025-01-08 09:29 UTC, michidold commented on apps/frontend/src/locales/de/translation.json
> +      "NotAbleToGetImapOption": "Auslesen der IMAP configuration ist nicht möglich",
"IMAP-Konfiguration"

2025-01-08 09:29 UTC, michidold commented on apps/api/src/mails/mails.service.ts
> +      );
This returns true even if its false in db. Change it to:
```typescript
this.imapRejectUnauthorized =
        getExtendedOptionValue(appConfigs, APPS.MAIL, ExtendedOptionKeys.MAIL_IMAP_TLS_REJECT_UNAUTHORIZED) === 'true';
```

2025-01-08 09:29 UTC, michidold commented on apps/api/src/mails/mails.service.ts
> +    if (!this.imapUrl || !this.imapPort || !this.imapSecure || !this.imapRejectUnauthorized) {
if its parsed to boolean the imapSecure and imapReject.. will throw a true, so we should remove them.
`if (!this.imapUrl || !this.imapPort)`

2025-01-08 09:29 UTC, michidold commented on apps/api/src/mails/mails.service.ts
> +        { seen: false, since: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) },
I would not filter for the last 7 days here. Maybe we set a filter in the frontend in future. Do we show all mails in mailsfeed?

2025-01-08 09:29 UTC, michidold commented on apps/frontend/src/locales/de/translation.json
> +    "mailImapUrlDescription": "Bitte gib eine gültige URL an um die Mailbox per IMAP zu verbinden",
Add the fact that http/https should be avoided, only the FQDN is needed.

2025-01-09 11:51 UTC, maierdominik commented on libs/src/appconfig/constants/extendedOptions/imapMailFeed.ts
> +];
The new Input types are added in following PR:
https://github.com/edulution-io/edulution-ui/pull/344

2025-01-09 12:00 UTC, maierdominik commented on apps/api/src/mails/mails.service.ts
> +        { seen: false, since: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000) },
All that are in the inbox and unseen, therefore the `seen` flag.
I added the seven days limit because of the following issue:
https://github.com/edulution-io/edulution-ui/issues/274

I will create a new branch with this filter in order to test it.

2025-01-09 12:09 UTC, maierdominik commented on apps/frontend/src/locales/de/translation.json
> +    "mailImapUrlDescription": "Bitte gib eine gültige URL an um die Mailbox per IMAP zu verbinden",
like this ?
![image](https://github.com/user-attachments/assets/39526261-8b58-45b0-8129-d56b7e299860)

2025-01-10 09:52 UTC, michidold commented on apps/frontend/src/locales/de/translation.json
> +    "mailImapUrlDescription": "Bitte gib eine gültige URL an um die Mailbox per IMAP zu verbinden",
The description is not displayed in AppConfig Page.

2025-01-10 10:00 UTC, michidold requested changes
One last thing, the description is missing in the appconfig page

2025-01-10 15:28 UTC, michidold approved these changes
Looks good

2025-01-10 15:32 UTC, merged