211 improve caching when building docker images
edulution-io/edulution-ui pull request #339
Opened 2024-12-20 10:05 UTC by michidold

Unfortunately the github summary shows 0% after all. But build time reduced by around 40 seconds.

Before:
![Bildschirmfoto vom 2024-12-20 11-00-29](https://github.com/user-attachments/assets/fc40ae89-7da4-4a70-9cc3-ed9d4fb6c2f1)
After:
![grafik](https://github.com/user-attachments/assets/1553437e-8554-4539-b6ba-dc22059933ff)

2024-12-20 12:08 UTC, TomlDev approved these changes
Nice 👍🏽

2024-12-20 16:04 UTC, michidold commented
Sorry, I changed only api and frontend tag builds. Will rework the build and test script as well

2025-01-08 09:07 UTC, TomlDev commented on .github/workflows/build-and-test.yml
> +          node-version: 18.x
Is there a reason for downgrading node here?

2025-01-08 09:08 UTC, TomlDev requested changes
Looks good, only the downgrad of node was not part of the PR description

2025-01-09 08:45 UTC, michidold commented on .github/workflows/build-and-test.yml
> +          node-version: 18.x
Think we should use the same version for dev and deployment. The release packages are built with 18 as well, so we should do the same for the build and test workflow.

2025-01-09 08:49 UTC, TomlDev approved these changes

2025-01-09 08:52 UTC, merged